// registry/default/components/ErrorBoundary.tsx
import { Component, type ReactNode } from 'react'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { AlertTriangle, RefreshCw, Home } from 'lucide-react'

interface Props {
  children: ReactNode
}

interface State {
  hasError: boolean
  error?: Error
}

export class ErrorBoundary extends Component<Props, State> {
  constructor(props: Props) {
    super(props)
    this.state = { hasError: false }
  }

  static getDerivedStateFromError(error: Error): State {
    return { hasError: true, error }
  }

  componentDidCatch(error: Error, errorInfo: React.ErrorInfo) {
    // Log error to console in development
    if (import.meta.env.DEV) {
      console.error('Error caught by boundary:', error, errorInfo)
    }
  }

  handleReload = () => {
    window.location.reload()
  }

  handleGoHome = () => {
    window.location.href = '/'
  }

  render() {
    if (this.state.hasError) {
      return (
        <div className="min-h-screen bg-background flex items-center justify-center p-4">
          <Card className="max-w-lg w-full">
            <CardHeader className="bg-destructive">
              <CardTitle className="flex items-center gap-3">
                <AlertTriangle className="h-6 w-6 stroke-[3]" />
                Something went wrong
              </CardTitle>
            </CardHeader>
            <CardContent className="pt-6 space-y-4">
              <p className="text-muted-foreground">
                An unexpected error occurred. This has been logged and we'll look into it.
              </p>
              {import.meta.env.DEV && this.state.error && (
                <pre className="bg-muted border-3 border-foreground p-4 text-sm overflow-x-auto">
                  <code>{this.state.error.message}</code>
                </pre>
              )}
              <div className="flex gap-3">
                <Button onClick={this.handleReload} className="gap-2">
                  <RefreshCw className="h-4 w-4" />
                  Reload Page
                </Button>
                <Button variant="outline" onClick={this.handleGoHome} className="gap-2">
                  <Home className="h-4 w-4" />
                  Go Home
                </Button>
              </div>
            </CardContent>
          </Card>
        </div>
      )
    }

    return this.props.children
  }
}

// packages/vue/src/components/ui/ErrorBoundary.vue
<script setup lang="ts">
import { ref, onErrorCaptured } from 'vue'
import Button from './Button.vue'
import Card from './Card.vue'
import CardHeader from './CardHeader.vue'
import CardTitle from './CardTitle.vue'
import CardContent from './CardContent.vue'
import { AlertTriangle, RefreshCw, Home } from 'lucide-vue-next'

const hasError = ref(false)
const error = ref<Error | null>(null)

onErrorCaptured((err) => {
  hasError.value = true
  error.value = err instanceof Error ? err : new Error(String(err))
  if (import.meta.env.DEV) {
    console.error('Error caught by boundary:', err)
  }
  // Returning false stops the error from propagating further up.
  return false
})

function handleReload() {
  window.location.reload()
}

function handleGoHome() {
  window.location.href = '/'
}
</script>

<template>
  <div
    v-if="hasError"
    class="min-h-screen bg-background flex items-center justify-center p-4"
  >
    <Card class="max-w-lg w-full">
      <CardHeader class="bg-destructive">
        <CardTitle class="flex items-center gap-3">
          <AlertTriangle class="h-6 w-6 stroke-[3]" />
          Something went wrong
        </CardTitle>
      </CardHeader>
      <CardContent class="pt-6 space-y-4">
        <p class="text-muted-foreground">
          An unexpected error occurred. This has been logged and we'll look into it.
        </p>
        <pre
          v-if="error && import.meta.env.DEV"
          class="bg-muted border-3 border-foreground p-4 text-sm overflow-x-auto"
        ><code>{{ error.message }}</code></pre>
        <div class="flex gap-3">
          <Button class="gap-2" @click="handleReload">
            <RefreshCw class="h-4 w-4" />
            Reload Page
          </Button>
          <Button variant="outline" class="gap-2" @click="handleGoHome">
            <Home class="h-4 w-4" />
            Go Home
          </Button>
        </div>
      </CardContent>
    </Card>
  </div>
  <slot v-else />
</template>
