// src/components/blocks/application/auth-forms.tsx
import * as React from 'react'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Checkbox } from '@/components/ui/checkbox'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { cn } from '@/lib/utils'
import { Eye, EyeOff, Mail, Lock, User, ArrowRight, Github, Chrome } from 'lucide-react'

// ============================================================================
// AUTH VARIANT 1: Login Form
// ============================================================================
export interface LoginFormProps {
  logo?: React.ReactNode
  title?: string
  description?: string
  onSubmit?: (data: { email: string; password: string; remember: boolean }) => void
  onForgotPassword?: () => void
  onSignUp?: () => void
  socialProviders?: Array<'google' | 'github'>
  className?: string
}

export function LoginForm({
  logo,
  title = 'Welcome back',
  description = 'Enter your credentials to access your account',
  onSubmit,
  onForgotPassword,
  onSignUp,
  socialProviders,
  className,
}: LoginFormProps) {
  const [formData, setFormData] = React.useState({
    email: '',
    password: '',
    remember: false,
  })
  const [showPassword, setShowPassword] = React.useState(false)

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault()
    onSubmit?.(formData)
  }

  return (
    <div className={cn('w-full max-w-md mx-auto', className)}>
      <Card>
        <CardHeader className="space-y-4 text-center">
          {logo && <div className="mx-auto">{logo}</div>}
          <div>
            <CardTitle className="text-2xl font-black uppercase">{title}</CardTitle>
            <CardDescription className="mt-2">{description}</CardDescription>
          </div>
        </CardHeader>
        <CardContent>
          <form onSubmit={handleSubmit} className="space-y-4">
            <div className="space-y-2">
              <Label htmlFor="email" className="font-bold uppercase text-xs">
                Email
              </Label>
              <div className="relative">
                <Mail className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground" />
                <Input
                  id="email"
                  type="email"
                  placeholder="you@example.com"
                  className="pl-10"
                  value={formData.email}
                  onChange={(e) => setFormData({ ...formData, email: e.target.value })}
                  required
                />
              </div>
            </div>

            <div className="space-y-2">
              <Label htmlFor="password" className="font-bold uppercase text-xs">
                Password
              </Label>
              <div className="relative">
                <Lock className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground" />
                <Input
                  id="password"
                  type={showPassword ? 'text' : 'password'}
                  placeholder="Enter your password"
                  className="pl-10 pr-10"
                  value={formData.password}
                  onChange={(e) => setFormData({ ...formData, password: e.target.value })}
                  required
                />
                <button
                  type="button"
                  aria-label={showPassword ? 'Hide password' : 'Show password'}
                  onClick={() => setShowPassword(!showPassword)}
                  className="absolute right-3 top-1/2 -translate-y-1/2 text-muted-foreground hover:text-foreground"
                >
                  {showPassword ? <EyeOff className="h-4 w-4" /> : <Eye className="h-4 w-4" />}
                </button>
              </div>
            </div>

            <div className="flex items-center justify-between">
              <div className="flex items-center space-x-2">
                <Checkbox
                  id="remember"
                  checked={formData.remember}
                  onCheckedChange={(checked) =>
                    setFormData({ ...formData, remember: checked as boolean })
                  }
                />
                <Label htmlFor="remember" className="text-sm font-medium cursor-pointer">
                  Remember me
                </Label>
              </div>
              {onForgotPassword && (
                <button
                  type="button"
                  onClick={onForgotPassword}
                  className="text-sm font-bold text-primary hover:underline"
                >
                  Forgot password?
                </button>
              )}
            </div>

            <Button type="submit" className="w-full" size="lg">
              Sign In
              <ArrowRight className="ml-2 h-4 w-4" />
            </Button>

            {socialProviders && socialProviders.length > 0 && (
              <>
                <div className="relative my-6">
                  <div className="absolute inset-0 flex items-center">
                    <div className="w-full border-t-2 border-foreground" />
                  </div>
                  <div className="relative flex justify-center text-xs uppercase">
                    <span className="bg-card px-2 text-muted-foreground font-bold">
                      Or continue with
                    </span>
                  </div>
                </div>

                <div className="grid grid-cols-2 gap-3">
                  {socialProviders.includes('google') && (
                    <Button variant="outline" type="button">
                      <Chrome className="mr-2 h-4 w-4" />
                      Google
                    </Button>
                  )}
                  {socialProviders.includes('github') && (
                    <Button variant="outline" type="button">
                      <Github className="mr-2 h-4 w-4" />
                      GitHub
                    </Button>
                  )}
                </div>
              </>
            )}

            {onSignUp && (
              <p className="text-center text-sm text-muted-foreground mt-4">
                Don't have an account?{' '}
                <button
                  type="button"
                  onClick={onSignUp}
                  className="font-bold text-primary hover:underline"
                >
                  Sign up
                </button>
              </p>
            )}
          </form>
        </CardContent>
      </Card>
    </div>
  )
}

// ============================================================================
// AUTH VARIANT 2: Sign Up Form
// ============================================================================
export interface SignUpFormProps {
  logo?: React.ReactNode
  title?: string
  description?: string
  onSubmit?: (data: { name: string; email: string; password: string; terms: boolean }) => void
  onSignIn?: () => void
  socialProviders?: Array<'google' | 'github'>
  termsUrl?: string
  privacyUrl?: string
  className?: string
}

export function SignUpForm({
  logo,
  title = 'Create an account',
  description = 'Enter your details to get started',
  onSubmit,
  onSignIn,
  socialProviders,
  termsUrl = '#',
  privacyUrl = '#',
  className,
}: SignUpFormProps) {
  const [formData, setFormData] = React.useState({
    name: '',
    email: '',
    password: '',
    terms: false,
  })
  const [showPassword, setShowPassword] = React.useState(false)
  const [termsError, setTermsError] = React.useState('')

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault()
    if (!formData.terms) {
      setTermsError('You must accept the terms to continue')
      return
    }
    setTermsError('')
    onSubmit?.(formData)
  }

  return (
    <div className={cn('w-full max-w-md mx-auto', className)}>
      <Card>
        <CardHeader className="space-y-4 text-center">
          {logo && <div className="mx-auto">{logo}</div>}
          <div>
            <CardTitle className="text-2xl font-black uppercase">{title}</CardTitle>
            <CardDescription className="mt-2">{description}</CardDescription>
          </div>
        </CardHeader>
        <CardContent>
          <form onSubmit={handleSubmit} className="space-y-4">
            <div className="space-y-2">
              <Label htmlFor="name" className="font-bold uppercase text-xs">
                Full Name
              </Label>
              <div className="relative">
                <User className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground" />
                <Input
                  id="name"
                  type="text"
                  placeholder="John Doe"
                  className="pl-10"
                  value={formData.name}
                  onChange={(e) => setFormData({ ...formData, name: e.target.value })}
                  required
                />
              </div>
            </div>

            <div className="space-y-2">
              <Label htmlFor="signup-email" className="font-bold uppercase text-xs">
                Email
              </Label>
              <div className="relative">
                <Mail className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground" />
                <Input
                  id="signup-email"
                  type="email"
                  placeholder="you@example.com"
                  className="pl-10"
                  value={formData.email}
                  onChange={(e) => setFormData({ ...formData, email: e.target.value })}
                  required
                />
              </div>
            </div>

            <div className="space-y-2">
              <Label htmlFor="signup-password" className="font-bold uppercase text-xs">
                Password
              </Label>
              <div className="relative">
                <Lock className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground" />
                <Input
                  id="signup-password"
                  type={showPassword ? 'text' : 'password'}
                  placeholder="Create a password"
                  className="pl-10 pr-10"
                  value={formData.password}
                  onChange={(e) => setFormData({ ...formData, password: e.target.value })}
                  required
                />
                <button
                  type="button"
                  aria-label={showPassword ? 'Hide password' : 'Show password'}
                  onClick={() => setShowPassword(!showPassword)}
                  className="absolute right-3 top-1/2 -translate-y-1/2 text-muted-foreground hover:text-foreground"
                >
                  {showPassword ? <EyeOff className="h-4 w-4" /> : <Eye className="h-4 w-4" />}
                </button>
              </div>
              <p className="text-xs text-muted-foreground">Must be at least 8 characters</p>
            </div>

            <div className="space-y-1">
              <div className="flex items-start space-x-2">
                <Checkbox
                  id="terms"
                  checked={formData.terms}
                  onCheckedChange={(checked) => {
                    setFormData({ ...formData, terms: checked as boolean })
                    if (checked) setTermsError('')
                  }}
                />
                <Label htmlFor="terms" className="text-sm leading-tight cursor-pointer">
                  I agree to the{' '}
                  <a href={termsUrl} className="font-bold text-primary hover:underline">
                    Terms of Service
                  </a>{' '}
                  and{' '}
                  <a href={privacyUrl} className="font-bold text-primary hover:underline">
                    Privacy Policy
                  </a>
                </Label>
              </div>
              {termsError && (
                <p className="text-xs text-destructive font-medium">{termsError}</p>
              )}
            </div>

            <Button type="submit" className="w-full" size="lg">
              Create Account
              <ArrowRight className="ml-2 h-4 w-4" />
            </Button>

            {socialProviders && socialProviders.length > 0 && (
              <>
                <div className="relative my-6">
                  <div className="absolute inset-0 flex items-center">
                    <div className="w-full border-t-2 border-foreground" />
                  </div>
                  <div className="relative flex justify-center text-xs uppercase">
                    <span className="bg-card px-2 text-muted-foreground font-bold">
                      Or continue with
                    </span>
                  </div>
                </div>

                <div className="grid grid-cols-2 gap-3">
                  {socialProviders.includes('google') && (
                    <Button variant="outline" type="button">
                      <Chrome className="mr-2 h-4 w-4" />
                      Google
                    </Button>
                  )}
                  {socialProviders.includes('github') && (
                    <Button variant="outline" type="button">
                      <Github className="mr-2 h-4 w-4" />
                      GitHub
                    </Button>
                  )}
                </div>
              </>
            )}

            {onSignIn && (
              <p className="text-center text-sm text-muted-foreground mt-4">
                Already have an account?{' '}
                <button
                  type="button"
                  onClick={onSignIn}
                  className="font-bold text-primary hover:underline"
                >
                  Sign in
                </button>
              </p>
            )}
          </form>
        </CardContent>
      </Card>
    </div>
  )
}

// ============================================================================
// AUTH VARIANT 3: Forgot Password Form
// ============================================================================
export interface ForgotPasswordFormProps {
  logo?: React.ReactNode
  title?: string
  description?: string
  onSubmit?: (email: string) => void
  onBackToLogin?: () => void
  className?: string
}

export function ForgotPasswordForm({
  logo,
  title = 'Forgot password?',
  description = "No worries, we'll send you reset instructions.",
  onSubmit,
  onBackToLogin,
  className,
}: ForgotPasswordFormProps) {
  const [email, setEmail] = React.useState('')
  const [submitted, setSubmitted] = React.useState(false)

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault()
    onSubmit?.(email)
    setSubmitted(true)
  }

  if (submitted) {
    return (
      <div className={cn('w-full max-w-md mx-auto', className)}>
        <Card>
          <CardContent className="pt-6 text-center space-y-4">
            <div className="w-16 h-16 mx-auto flex items-center justify-center border-3 border-foreground bg-success/20 shadow-[4px_4px_0px_hsl(var(--shadow-color))]">
              <Mail className="h-8 w-8 text-success" />
            </div>
            <div>
              <h3 className="text-xl font-black uppercase">Check your email</h3>
              <p className="text-sm text-muted-foreground mt-2">
                We sent a password reset link to{' '}
                <span className="font-bold text-foreground">{email}</span>
              </p>
            </div>
            <Button variant="outline" className="w-full" onClick={onBackToLogin}>
              Back to login
            </Button>
            <p className="text-xs text-muted-foreground">
              Didn't receive the email?{' '}
              <button
                type="button"
                onClick={() => setSubmitted(false)}
                className="font-bold text-primary hover:underline"
              >
                Click to resend
              </button>
            </p>
          </CardContent>
        </Card>
      </div>
    )
  }

  return (
    <div className={cn('w-full max-w-md mx-auto', className)}>
      <Card>
        <CardHeader className="space-y-4 text-center">
          {logo && <div className="mx-auto">{logo}</div>}
          <div>
            <CardTitle className="text-2xl font-black uppercase">{title}</CardTitle>
            <CardDescription className="mt-2">{description}</CardDescription>
          </div>
        </CardHeader>
        <CardContent>
          <form onSubmit={handleSubmit} className="space-y-4">
            <div className="space-y-2">
              <Label htmlFor="reset-email" className="font-bold uppercase text-xs">
                Email
              </Label>
              <div className="relative">
                <Mail className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground" />
                <Input
                  id="reset-email"
                  type="email"
                  placeholder="you@example.com"
                  className="pl-10"
                  value={email}
                  onChange={(e) => setEmail(e.target.value)}
                  required
                />
              </div>
            </div>

            <Button type="submit" className="w-full" size="lg">
              Send Reset Link
              <ArrowRight className="ml-2 h-4 w-4" />
            </Button>

            {onBackToLogin && (
              <Button
                type="button"
                variant="ghost"
                className="w-full"
                onClick={onBackToLogin}
              >
                Back to login
              </Button>
            )}
          </form>
        </CardContent>
      </Card>
    </div>
  )
}

// ============================================================================
// AUTH VARIANT 4: OTP Verification Form
// ============================================================================
export interface OTPVerificationFormProps {
  logo?: React.ReactNode
  title?: string
  description?: string
  email?: string
  length?: number
  onSubmit?: (otp: string) => void
  onResend?: () => void
  onBackToLogin?: () => void
  className?: string
}

export function OTPVerificationForm({
  logo,
  title = 'Verify your email',
  description,
  email,
  length = 6,
  onSubmit,
  onResend,
  onBackToLogin,
  className,
}: OTPVerificationFormProps) {
  const [otp, setOtp] = React.useState<string[]>(new Array(length).fill(''))
  const inputRefs = React.useRef<HTMLInputElement[]>([])
  const hasSubmitted = React.useRef(false)

  const handleChange = (index: number, value: string) => {
    if (!/^\d*$/.test(value)) return

    const newOtp = [...otp]
    newOtp[index] = value.slice(-1)
    setOtp(newOtp)

    // Reset guard so user can re-submit after editing a filled OTP
    hasSubmitted.current = false

    if (value && index < length - 1) {
      inputRefs.current[index + 1]?.focus()
    }

    // Use local newOtp (not stale hasSubmitted.current) to check auto-submit
    if (newOtp.every((digit) => digit !== '') && newOtp.join('').length === length) {
      hasSubmitted.current = true
      onSubmit?.(newOtp.join(''))
    }
  }

  const handleKeyDown = (index: number, e: React.KeyboardEvent<HTMLInputElement>) => {
    if (e.key === 'Backspace' && !otp[index] && index > 0) {
      inputRefs.current[index - 1]?.focus()
    }
  }

  const handlePaste = (e: React.ClipboardEvent) => {
    e.preventDefault()
    const pastedData = e.clipboardData.getData('text').slice(0, length)
    if (!/^\d+$/.test(pastedData)) return

    const newOtp = [...otp]
    pastedData.split('').forEach((char, index) => {
      if (index < length) newOtp[index] = char
    })
    setOtp(newOtp)

    if (newOtp.every((digit) => digit !== '') && !hasSubmitted.current) {
      hasSubmitted.current = true
      onSubmit?.(newOtp.join(''))
    }
  }

  return (
    <div className={cn('w-full max-w-md mx-auto', className)}>
      <Card>
        <CardHeader className="space-y-4 text-center">
          {logo && <div className="mx-auto">{logo}</div>}
          <div>
            <CardTitle className="text-2xl font-black uppercase">{title}</CardTitle>
            <CardDescription className="mt-2">
              {description ||
                `We sent a ${length}-digit code to ${email || 'your email'}. Enter it below.`}
            </CardDescription>
          </div>
        </CardHeader>
        <CardContent className="space-y-6">
          <div className="flex justify-center gap-2">
            {otp.map((digit, index) => (
              <Input
                key={`otp-digit-${index}`}
                ref={(el) => { if (el) inputRefs.current[index] = el }}
                type="text"
                inputMode="numeric"
                maxLength={1}
                aria-label={`Digit ${index + 1} of ${length}`}
                value={digit}
                onChange={(e) => handleChange(index, e.target.value)}
                onKeyDown={(e) => handleKeyDown(index, e)}
                onPaste={handlePaste}
                className="w-12 h-14 text-center text-2xl font-black"
              />
            ))}
          </div>

          <Button
            className="w-full"
            size="lg"
            onClick={() => {
              if (!hasSubmitted.current) {
                hasSubmitted.current = true
                onSubmit?.(otp.join(''))
              }
            }}
            disabled={otp.some((digit) => digit === '')}
          >
            Verify
            <ArrowRight className="ml-2 h-4 w-4" />
          </Button>

          <div className="text-center space-y-2">
            {onResend && (
              <p className="text-sm text-muted-foreground">
                Didn't receive a code?{' '}
                <button
                  type="button"
                  onClick={onResend}
                  className="font-bold text-primary hover:underline"
                >
                  Resend
                </button>
              </p>
            )}
            {onBackToLogin && (
              <Button variant="ghost" size="sm" onClick={onBackToLogin}>
                Back to login
              </Button>
            )}
          </div>
        </CardContent>
      </Card>
    </div>
  )
}

// ============================================================================
// AUTH VARIANT 5: Split Auth Layout
// ============================================================================
export interface AuthSplitLayoutProps {
  children: React.ReactNode
  brandContent?: React.ReactNode
  brandBackground?: string
  position?: 'left' | 'right'
  className?: string
}

export function AuthSplitLayout({
  children,
  brandContent,
  brandBackground = 'bg-primary',
  position = 'left',
  className,
}: AuthSplitLayoutProps) {
  return (
    <div className={cn('min-h-screen flex', className)}>
      {position === 'left' && brandContent && (
        <div
          className={cn(
            'hidden lg:flex lg:w-1/2 flex-col justify-center p-12',
            brandBackground
          )}
        >
          {brandContent}
        </div>
      )}

      <div className="flex-1 flex items-center justify-center p-4 md:p-8">
        {children}
      </div>

      {position === 'right' && brandContent && (
        <div
          className={cn(
            'hidden lg:flex lg:w-1/2 flex-col justify-center p-12',
            brandBackground
          )}
        >
          {brandContent}
        </div>
      )}
    </div>
  )
}

// ============================================================================
// Export all variants
// ============================================================================
export const AuthForms = {
  Login: LoginForm,
  SignUp: SignUpForm,
  ForgotPassword: ForgotPasswordForm,
  OTPVerification: OTPVerificationForm,
  SplitLayout: AuthSplitLayout,
}

// packages/vue/src/components/blocks/application/AuthForms.vue
<script setup lang="ts">
import { ref } from 'vue'
import { cn } from '@/lib/utils'
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from '@/components/ui'
import Button from '@/components/ui/Button.vue'
import Input from '@/components/ui/Input.vue'
import Label from '@/components/ui/Label.vue'
import Checkbox from '@/components/ui/Checkbox.vue'
import { Mail, Lock, User, Eye, EyeOff, ArrowLeft, Github } from 'lucide-vue-next'

type AuthFormVariant = 'login' | 'signup' | 'forgotPassword' | 'otpVerification' | 'splitLayout'

type SocialProvider = 'google' | 'github' | 'twitter'

interface AuthFormsProps {
  variant?: AuthFormVariant
  socialProviders?: SocialProvider[]
  backgroundImage?: string
  class?: string
}

const props = withDefaults(defineProps<AuthFormsProps>(), {
  variant: 'login',
  socialProviders: () => [],
})

const emit = defineEmits<{
  (e: 'submit', data: Record<string, string>): void
  (e: 'socialLogin', provider: SocialProvider): void
  (e: 'back'): void
}>()

const showPassword = ref(false)
const email = ref('')
const password = ref('')
const name = ref('')
const confirmPassword = ref('')
const rememberMe = ref(false)
const otpValues = ref(['', '', '', '', '', ''])
const inputRefs = ref<HTMLInputElement[]>([])

const handleOtpInput = (index: number, event: Event) => {
  const target = event.target as HTMLInputElement
  const value = target.value

  if (value && index < 5) {
    inputRefs.value[index + 1]?.focus()
  }
}

const handleOtpKeydown = (index: number, event: KeyboardEvent) => {
  if (event.key === 'Backspace' && !otpValues.value[index] && index > 0) {
    inputRefs.value[index - 1]?.focus()
  }
}

const handleOtpPaste = (event: ClipboardEvent) => {
  event.preventDefault()
  const pasted = event.clipboardData?.getData('text') ?? ''
  const digits = pasted.replace(/\D/g, '').slice(0, 6)
  if (!digits) return
  const newOtp = [...otpValues.value]
  digits.split('').forEach((char, i) => { if (i < 6) newOtp[i] = char })
  otpValues.value = newOtp
  const focusIndex = Math.min(digits.length, 5)
  inputRefs.value[focusIndex]?.focus()
  if (digits.length === 6) {
    handleSubmit()
  }
}

const handleSubmit = () => {
  if (props.variant === 'login') {
    emit('submit', { email: email.value, password: password.value, rememberMe: String(rememberMe.value) })
  } else if (props.variant === 'signup') {
    emit('submit', { name: name.value, email: email.value, password: password.value })
  } else if (props.variant === 'forgotPassword') {
    emit('submit', { email: email.value })
  } else if (props.variant === 'otpVerification') {
    emit('submit', { otp: otpValues.value.join('') })
  }
}
</script>

<template>
  <!-- Login Variant -->
  <div
    v-if="variant === 'login'"
    :class="cn('flex items-center justify-center min-h-screen p-4', props.class)"
  >
    <Card class="w-full max-w-md shadow-[8px_8px_0px_hsl(var(--shadow-color))]">
      <CardHeader class="text-center">
        <CardTitle class="text-2xl uppercase">Welcome Back</CardTitle>
        <CardDescription>Sign in to your account to continue</CardDescription>
      </CardHeader>
      <CardContent>
        <form class="space-y-4" @submit.prevent="handleSubmit">
          <div class="space-y-2">
            <Label for="email">Email</Label>
            <div class="relative">
              <Mail class="absolute left-3 top-1/2 -translate-y-1/2 h-5 w-5 text-muted-foreground" />
              <Input id="email" v-model="email" type="email" autocomplete="email" placeholder="you@example.com" class="pl-10" required />
            </div>
          </div>
          <div class="space-y-2">
            <Label for="password">Password</Label>
            <div class="relative">
              <Lock class="absolute left-3 top-1/2 -translate-y-1/2 h-5 w-5 text-muted-foreground" />
              <Input
                id="password"
                v-model="password"
                :type="showPassword ? 'text' : 'password'"
                autocomplete="current-password"
                placeholder="••••••••"
                class="pl-10 pr-10"
                required
              />
              <button
                type="button"
                :aria-label="showPassword ? 'Hide password' : 'Show password'"
                class="absolute right-3 top-1/2 -translate-y-1/2 text-muted-foreground hover:text-foreground"
                @click="showPassword = !showPassword"
              >
                <EyeOff v-if="showPassword" class="h-5 w-5" />
                <Eye v-else class="h-5 w-5" />
              </button>
            </div>
          </div>
          <div class="flex items-center justify-between">
            <div class="flex items-center gap-2">
              <Checkbox id="remember" v-model:checked="rememberMe" />
              <Label for="remember" class="text-sm cursor-pointer">Remember me</Label>
            </div>
            <a href="#" class="text-sm text-primary hover:underline font-medium">Forgot password?</a>
          </div>
          <Button type="submit" class="w-full">Sign In</Button>
        </form>

        <div v-if="socialProviders.length > 0" class="mt-6">
          <div class="relative">
            <div class="absolute inset-0 flex items-center">
              <div class="w-full border-t-3 border-foreground" />
            </div>
            <div class="relative flex justify-center text-sm">
              <span class="bg-card px-2 text-muted-foreground font-bold uppercase">Or continue with</span>
            </div>
          </div>
          <div class="mt-4 flex gap-3">
            <Button
              v-for="provider in socialProviders"
              :key="provider"
              variant="outline"
              class="flex-1"
              @click="emit('socialLogin', provider)"
            >
              <Github v-if="provider === 'github'" class="h-5 w-5" />
              <span v-else class="font-bold">{{ provider[0].toUpperCase() }}</span>
            </Button>
          </div>
        </div>
      </CardContent>
      <CardFooter class="justify-center">
        <p class="text-sm text-muted-foreground">
          Don't have an account?
          <a href="#" class="text-primary hover:underline font-bold">Sign up</a>
        </p>
      </CardFooter>
    </Card>
  </div>

  <!-- SignUp Variant -->
  <div
    v-else-if="variant === 'signup'"
    :class="cn('flex items-center justify-center min-h-screen p-4', props.class)"
  >
    <Card class="w-full max-w-md shadow-[8px_8px_0px_hsl(var(--shadow-color))]">
      <CardHeader class="text-center">
        <CardTitle class="text-2xl uppercase">Create Account</CardTitle>
        <CardDescription>Enter your details to get started</CardDescription>
      </CardHeader>
      <CardContent>
        <form class="space-y-4" @submit.prevent="handleSubmit">
          <div class="space-y-2">
            <Label for="name">Full Name</Label>
            <div class="relative">
              <User class="absolute left-3 top-1/2 -translate-y-1/2 h-5 w-5 text-muted-foreground" />
              <Input id="name" v-model="name" placeholder="John Doe" class="pl-10" required />
            </div>
          </div>
          <div class="space-y-2">
            <Label for="signup-email">Email</Label>
            <div class="relative">
              <Mail class="absolute left-3 top-1/2 -translate-y-1/2 h-5 w-5 text-muted-foreground" />
              <Input id="signup-email" v-model="email" type="email" autocomplete="email" placeholder="you@example.com" class="pl-10" required />
            </div>
          </div>
          <div class="space-y-2">
            <Label for="signup-password">Password</Label>
            <div class="relative">
              <Lock class="absolute left-3 top-1/2 -translate-y-1/2 h-5 w-5 text-muted-foreground" />
              <Input id="signup-password" v-model="password" type="password" autocomplete="new-password" placeholder="••••••••" class="pl-10" required />
            </div>
          </div>
          <div class="space-y-2">
            <Label for="confirm-password">Confirm Password</Label>
            <div class="relative">
              <Lock class="absolute left-3 top-1/2 -translate-y-1/2 h-5 w-5 text-muted-foreground" />
              <Input id="confirm-password" v-model="confirmPassword" type="password" autocomplete="new-password" placeholder="••••••••" class="pl-10" required />
            </div>
          </div>
          <Button type="submit" class="w-full">Create Account</Button>
        </form>
      </CardContent>
      <CardFooter class="justify-center">
        <p class="text-sm text-muted-foreground">
          Already have an account?
          <a href="#" class="text-primary hover:underline font-bold">Sign in</a>
        </p>
      </CardFooter>
    </Card>
  </div>

  <!-- ForgotPassword Variant -->
  <div
    v-else-if="variant === 'forgotPassword'"
    :class="cn('flex items-center justify-center min-h-screen p-4', props.class)"
  >
    <Card class="w-full max-w-md shadow-[8px_8px_0px_hsl(var(--shadow-color))]">
      <CardHeader class="text-center">
        <CardTitle class="text-2xl uppercase">Reset Password</CardTitle>
        <CardDescription>
          Enter your email and we'll send you a link to reset your password
        </CardDescription>
      </CardHeader>
      <CardContent>
        <form class="space-y-4" @submit.prevent="handleSubmit">
          <div class="space-y-2">
            <Label for="reset-email">Email</Label>
            <div class="relative">
              <Mail class="absolute left-3 top-1/2 -translate-y-1/2 h-5 w-5 text-muted-foreground" />
              <Input id="reset-email" v-model="email" type="email" placeholder="you@example.com" class="pl-10" required />
            </div>
          </div>
          <Button type="submit" class="w-full">Send Reset Link</Button>
        </form>
      </CardContent>
      <CardFooter class="justify-center">
        <Button variant="ghost" class="gap-2" @click="emit('back')">
          <ArrowLeft class="h-4 w-4" />
          Back to login
        </Button>
      </CardFooter>
    </Card>
  </div>

  <!-- OTP Verification Variant -->
  <div
    v-else-if="variant === 'otpVerification'"
    :class="cn('flex items-center justify-center min-h-screen p-4', props.class)"
  >
    <Card class="w-full max-w-md shadow-[8px_8px_0px_hsl(var(--shadow-color))]">
      <CardHeader class="text-center">
        <CardTitle class="text-2xl uppercase">Verify Code</CardTitle>
        <CardDescription>
          Enter the 6-digit code sent to your email
        </CardDescription>
      </CardHeader>
      <CardContent>
        <form class="space-y-6" @submit.prevent="handleSubmit">
          <div class="flex justify-center gap-3">
            <input
              v-for="(_, index) in otpValues"
              :key="`otp-digit-${index}`"
              :ref="(el) => { if (el) inputRefs[index] = el as HTMLInputElement }"
              v-model="otpValues[index]"
              type="text"
              inputmode="numeric"
              maxlength="1"
              :aria-label="`Digit ${index + 1} of 6`"
              class="w-12 h-14 text-center text-2xl font-black border-3 border-foreground shadow-[3px_3px_0px_hsl(var(--shadow-color))] focus:outline-none focus:ring-2 focus:ring-primary"
              @input="(e) => handleOtpInput(index, e)"
              @keydown="(e) => handleOtpKeydown(index, e)"
              @paste="handleOtpPaste"
            />
          </div>
          <Button type="submit" class="w-full">Verify</Button>
        </form>
      </CardContent>
      <CardFooter class="flex-col gap-4">
        <p class="text-sm text-muted-foreground text-center">
          Didn't receive the code?
          <button type="button" class="text-primary hover:underline font-bold">Resend</button>
        </p>
        <Button variant="ghost" class="gap-2" @click="emit('back')">
          <ArrowLeft class="h-4 w-4" />
          Back
        </Button>
      </CardFooter>
    </Card>
  </div>

  <!-- SplitLayout Variant -->
  <div
    v-else-if="variant === 'splitLayout'"
    :class="cn('grid lg:grid-cols-2 min-h-screen', props.class)"
  >
    <div
      class="hidden lg:flex flex-col justify-between p-12 bg-primary text-primary-foreground"
      :style="backgroundImage ? { backgroundImage: `url(${backgroundImage})`, backgroundSize: 'cover', backgroundPosition: 'center' } : {}"
    >
      <div class="flex items-center gap-3">
        <div class="w-10 h-10 border-3 border-primary-foreground" />
        <span class="font-black uppercase text-xl">BoldKit</span>
      </div>
      <div class="space-y-4">
        <h2 class="text-4xl font-black uppercase">Build bold interfaces</h2>
        <p class="text-primary-foreground/80 text-lg font-medium">
          Join thousands of developers building stunning applications with BoldKit.
        </p>
      </div>
      <p class="text-sm text-primary-foreground/60">
        © 2024 BoldKit. All rights reserved.
      </p>
    </div>

    <div class="flex items-center justify-center p-8 bg-background">
      <div class="w-full max-w-md space-y-8">
        <div class="text-center">
          <h1 class="text-3xl font-black uppercase">Sign In</h1>
          <p class="text-muted-foreground mt-2">Enter your credentials to continue</p>
        </div>

        <form class="space-y-4" @submit.prevent="handleSubmit">
          <div class="space-y-2">
            <Label for="split-email">Email</Label>
            <Input id="split-email" v-model="email" type="email" autocomplete="email" placeholder="you@example.com" required />
          </div>
          <div class="space-y-2">
            <Label for="split-password">Password</Label>
            <Input id="split-password" v-model="password" type="password" autocomplete="current-password" placeholder="••••••••" required />
          </div>
          <Button type="submit" class="w-full">Sign In</Button>
        </form>

        <div v-if="socialProviders.length > 0">
          <div class="relative">
            <div class="absolute inset-0 flex items-center">
              <div class="w-full border-t-3 border-foreground" />
            </div>
            <div class="relative flex justify-center text-sm">
              <span class="bg-background px-2 text-muted-foreground font-bold uppercase">Or</span>
            </div>
          </div>
          <div class="mt-4 flex gap-3">
            <Button
              v-for="provider in socialProviders"
              :key="provider"
              variant="outline"
              class="flex-1"
              @click="emit('socialLogin', provider)"
            >
              <Github v-if="provider === 'github'" class="h-5 w-5 mr-2" />
              {{ provider }}
            </Button>
          </div>
        </div>

        <p class="text-center text-sm text-muted-foreground">
          Don't have an account?
          <a href="#" class="text-primary hover:underline font-bold">Sign up</a>
        </p>
      </div>
    </div>
  </div>
</template>
