// src/components/blocks/application/invoice.tsx
import * as React from 'react'
import { Button } from '@/components/ui/button'
import { Separator } from '@/components/ui/separator'
import { cn } from '@/lib/utils'
import { Download, Printer, Mail, Check, Clock, AlertCircle } from 'lucide-react'

// ============================================================================
// Common Types
// ============================================================================
export interface InvoiceItem {
  description: string
  quantity: number
  unitPrice: number
  total?: number
}

export interface InvoiceAddress {
  name: string
  company?: string
  address: string
  city: string
  state?: string
  zip: string
  country?: string
  email?: string
  phone?: string
}

export interface InvoiceData {
  invoiceNumber: string
  issueDate: string
  dueDate: string
  status?: 'paid' | 'pending' | 'overdue'
  from: InvoiceAddress
  to: InvoiceAddress
  items: InvoiceItem[]
  subtotal: number
  tax?: { label: string; rate: number; amount: number }
  discount?: { label: string; amount: number }
  total: number
  notes?: string
  terms?: string
  paymentInfo?: {
    bankName?: string
    accountNumber?: string
    routingNumber?: string
    paymentMethods?: string[]
  }
}

// ============================================================================
// INVOICE VARIANT 1: Full Invoice
// ============================================================================
export interface InvoiceProps {
  data: InvoiceData
  logo?: React.ReactNode
  onDownload?: () => void
  onPrint?: () => void
  onSendEmail?: () => void
  className?: string
}

export function Invoice({
  data,
  logo,
  onDownload,
  onPrint,
  onSendEmail,
  className,
}: InvoiceProps) {
  const computedSubtotal = data.items.reduce(
    (sum, item) => sum + (item.total ?? item.quantity * item.unitPrice),
    0
  )
  const computedTotal =
    computedSubtotal +
    (data.tax?.amount ?? 0) -
    (data.discount?.amount ?? 0)

  if (import.meta.env.DEV) {
    if (Math.abs(computedSubtotal - data.subtotal) > 0.01) {
      console.warn(
        `[Invoice] subtotal mismatch: passed ${data.subtotal.toFixed(2)}, computed ${computedSubtotal.toFixed(2)}`
      )
    }
    if (Math.abs(computedTotal - data.total) > 0.01) {
      console.warn(
        `[Invoice] total mismatch: passed ${data.total.toFixed(2)}, computed ${computedTotal.toFixed(2)}`
      )
    }
  }

  const statusConfig = {
    paid: { bg: 'bg-success', text: 'text-success-foreground', icon: Check },
    pending: { bg: 'bg-warning', text: 'text-warning-foreground', icon: Clock },
    overdue: { bg: 'bg-destructive', text: 'text-destructive-foreground', icon: AlertCircle },
  }

  const status = data.status ? statusConfig[data.status] : null

  return (
    <div className={cn('max-w-4xl mx-auto', className)}>
      {/* Actions Bar */}
      <div className="flex items-center justify-between mb-6 print:hidden">
        <h1 className="text-2xl font-black uppercase">Invoice</h1>
        <div className="flex gap-2">
          {onSendEmail && (
            <Button variant="outline" size="sm" onClick={onSendEmail}>
              <Mail className="mr-2 h-4 w-4" />
              Email
            </Button>
          )}
          {onPrint && (
            <Button variant="outline" size="sm" onClick={onPrint}>
              <Printer className="mr-2 h-4 w-4" />
              Print
            </Button>
          )}
          {onDownload && (
            <Button size="sm" onClick={onDownload}>
              <Download className="mr-2 h-4 w-4" />
              Download
            </Button>
          )}
        </div>
      </div>

      {/* Invoice Document */}
      <div className="border-3 border-foreground bg-card shadow-[8px_8px_0px_hsl(var(--shadow-color))] print:border-0 print:shadow-none">
        <div className="p-8 md:p-12">
          {/* Header */}
          <div className="flex flex-col md:flex-row md:items-start md:justify-between gap-6 mb-8">
            <div>
              {logo && <div className="mb-4">{logo}</div>}
              <AddressBlock address={data.from} />
            </div>

            <div className="text-left md:text-right space-y-2">
              <h2 className="text-4xl font-black uppercase tracking-tight">Invoice</h2>
              <div className="space-y-1 text-sm">
                <p>
                  <span className="font-bold uppercase text-muted-foreground">Invoice #:</span>{' '}
                  <span className="font-medium">{data.invoiceNumber}</span>
                </p>
                <p>
                  <span className="font-bold uppercase text-muted-foreground">Issue Date:</span>{' '}
                  <span className="font-medium">{data.issueDate}</span>
                </p>
                <p>
                  <span className="font-bold uppercase text-muted-foreground">Due Date:</span>{' '}
                  <span className="font-medium">{data.dueDate}</span>
                </p>
              </div>
              {status && (
                <div
                  className={cn(
                    'inline-flex items-center gap-1 px-3 py-1 font-bold uppercase text-xs',
                    status.bg,
                    status.text
                  )}
                >
                  <status.icon className="h-3 w-3" />
                  {data.status}
                </div>
              )}
            </div>
          </div>

          {/* Bill To */}
          <div className="mb-8 p-4 border-3 border-foreground bg-muted/30">
            <p className="font-bold uppercase text-xs text-muted-foreground mb-2">Bill To</p>
            <AddressBlock address={data.to} />
          </div>

          {/* Items Table */}
          <div className="mb-8 overflow-x-auto">
            <table className="w-full">
              <thead>
                <tr className="border-b-3 border-foreground">
                  <th className="text-left py-3 font-black uppercase text-sm">Description</th>
                  <th className="text-center py-3 font-black uppercase text-sm w-24">Qty</th>
                  <th className="text-right py-3 font-black uppercase text-sm w-32">Unit Price</th>
                  <th className="text-right py-3 font-black uppercase text-sm w-32">Total</th>
                </tr>
              </thead>
              <tbody>
                {data.items.map((item) => (
                  <tr key={`invoice-item-${item.description}`} className="border-b border-foreground/20">
                    <td className="py-4">{item.description}</td>
                    <td className="py-4 text-center">{item.quantity}</td>
                    <td className="py-4 text-right font-mono">${item.unitPrice.toFixed(2)}</td>
                    <td className="py-4 text-right font-mono font-bold">
                      ${(item.total || item.quantity * item.unitPrice).toFixed(2)}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>

          {/* Totals */}
          <div className="flex justify-end mb-8">
            <div className="w-full max-w-xs space-y-2">
              <div className="flex justify-between py-2">
                <span className="text-muted-foreground">Subtotal</span>
                <span className="font-mono font-bold">${data.subtotal.toFixed(2)}</span>
              </div>
              {data.tax && (
                <div className="flex justify-between py-2">
                  <span className="text-muted-foreground">
                    {data.tax.label} ({data.tax.rate}%)
                  </span>
                  <span className="font-mono">${data.tax.amount.toFixed(2)}</span>
                </div>
              )}
              {data.discount && (
                <div className="flex justify-between py-2 text-success">
                  <span>{data.discount.label}</span>
                  <span className="font-mono">-${data.discount.amount.toFixed(2)}</span>
                </div>
              )}
              <Separator className="bg-foreground h-[2px]" />
              <div className="flex justify-between py-2">
                <span className="text-lg font-black uppercase">Total</span>
                <span className="text-2xl font-black font-mono">${data.total.toFixed(2)}</span>
              </div>
            </div>
          </div>

          {/* Payment Info */}
          {data.paymentInfo && (
            <div className="mb-8 p-4 border-3 border-foreground bg-primary/5">
              <p className="font-bold uppercase text-xs text-muted-foreground mb-3">
                Payment Information
              </p>
              <div className="grid md:grid-cols-2 gap-4 text-sm">
                {data.paymentInfo.bankName && (
                  <div>
                    <p className="font-bold">Bank Name</p>
                    <p className="text-muted-foreground">{data.paymentInfo.bankName}</p>
                  </div>
                )}
                {data.paymentInfo.accountNumber && (
                  <div>
                    <p className="font-bold">Account Number</p>
                    <p className="text-muted-foreground font-mono">
                      {data.paymentInfo.accountNumber}
                    </p>
                  </div>
                )}
                {data.paymentInfo.routingNumber && (
                  <div>
                    <p className="font-bold">Routing Number</p>
                    <p className="text-muted-foreground font-mono">
                      {data.paymentInfo.routingNumber}
                    </p>
                  </div>
                )}
                {data.paymentInfo.paymentMethods && (
                  <div>
                    <p className="font-bold">Accepted Methods</p>
                    <p className="text-muted-foreground">
                      {data.paymentInfo.paymentMethods.join(', ')}
                    </p>
                  </div>
                )}
              </div>
            </div>
          )}

          {/* Notes & Terms */}
          {(data.notes || data.terms) && (
            <div className="grid md:grid-cols-2 gap-6 text-sm">
              {data.notes && (
                <div>
                  <p className="font-bold uppercase text-xs text-muted-foreground mb-2">Notes</p>
                  <p className="text-muted-foreground">{data.notes}</p>
                </div>
              )}
              {data.terms && (
                <div>
                  <p className="font-bold uppercase text-xs text-muted-foreground mb-2">
                    Terms & Conditions
                  </p>
                  <p className="text-muted-foreground">{data.terms}</p>
                </div>
              )}
            </div>
          )}
        </div>
      </div>
    </div>
  )
}

// ============================================================================
// INVOICE VARIANT 2: Compact Receipt
// ============================================================================
export interface ReceiptData {
  receiptNumber: string
  date: string
  merchant: {
    name: string
    address?: string
    phone?: string
  }
  items: Array<{
    name: string
    quantity?: number
    price: number
  }>
  subtotal: number
  tax?: number
  total: number
  paymentMethod?: string
  cardLast4?: string
}

export interface ReceiptProps {
  data: ReceiptData
  logo?: React.ReactNode
  onDownload?: () => void
  className?: string
}

export function Receipt({
  data,
  logo,
  onDownload,
  className,
}: ReceiptProps) {
  return (
    <div className={cn('max-w-sm mx-auto', className)}>
      <div className="border-3 border-foreground bg-card shadow-[6px_6px_0px_hsl(var(--shadow-color))]">
        <div className="p-6 space-y-6">
          {/* Header */}
          <div className="text-center space-y-2">
            {logo && <div className="flex justify-center mb-4">{logo}</div>}
            <h2 className="font-black uppercase text-xl">{data.merchant.name}</h2>
            {data.merchant.address && (
              <p className="text-sm text-muted-foreground">{data.merchant.address}</p>
            )}
            {data.merchant.phone && (
              <p className="text-sm text-muted-foreground">{data.merchant.phone}</p>
            )}
          </div>

          <Separator className="bg-foreground h-[2px] border-dashed" />

          {/* Receipt Info */}
          <div className="text-center space-y-1 text-sm">
            <p className="font-bold uppercase">Receipt #{data.receiptNumber}</p>
            <p className="text-muted-foreground">{data.date}</p>
          </div>

          <Separator className="bg-foreground h-[2px] border-dashed" />

          {/* Items */}
          <div className="space-y-2">
            {data.items.map((item) => (
              <div key={item.name} className="flex justify-between text-sm">
                <span>
                  {item.quantity && item.quantity > 1 && `${item.quantity}x `}
                  {item.name}
                </span>
                <span className="font-mono">${item.price.toFixed(2)}</span>
              </div>
            ))}
          </div>

          <Separator className="bg-foreground h-[2px] border-dashed" />

          {/* Totals */}
          <div className="space-y-2">
            <div className="flex justify-between text-sm">
              <span className="text-muted-foreground">Subtotal</span>
              <span className="font-mono">${data.subtotal.toFixed(2)}</span>
            </div>
            {data.tax !== undefined && (
              <div className="flex justify-between text-sm">
                <span className="text-muted-foreground">Tax</span>
                <span className="font-mono">${data.tax.toFixed(2)}</span>
              </div>
            )}
            <div className="flex justify-between font-bold">
              <span className="uppercase">Total</span>
              <span className="font-mono text-lg">${data.total.toFixed(2)}</span>
            </div>
          </div>

          <Separator className="bg-foreground h-[2px] border-dashed" />

          {/* Payment Method */}
          {data.paymentMethod && (
            <div className="text-center text-sm space-y-1">
              <p className="text-muted-foreground">Paid with {data.paymentMethod}</p>
              {data.cardLast4 && (
                <p className="font-mono">•••• {data.cardLast4}</p>
              )}
            </div>
          )}

          {/* Thank You */}
          <div className="text-center">
            <p className="font-bold uppercase text-sm">Thank You!</p>
          </div>

          {/* Download */}
          {onDownload && (
            <Button
              variant="outline"
              className="w-full print:hidden"
              onClick={onDownload}
            >
              <Download className="mr-2 h-4 w-4" />
              Download Receipt
            </Button>
          )}
        </div>
      </div>
    </div>
  )
}

// ============================================================================
// INVOICE VARIANT 3: Invoice Summary Card
// ============================================================================
export interface InvoiceSummaryProps {
  invoiceNumber: string
  clientName: string
  issueDate: string
  dueDate: string
  amount: number
  status: 'paid' | 'pending' | 'overdue'
  onView?: () => void
  onDownload?: () => void
  className?: string
}

export function InvoiceSummary({
  invoiceNumber,
  clientName,
  issueDate,
  dueDate,
  amount,
  status,
  onView,
  onDownload,
  className,
}: InvoiceSummaryProps) {
  const statusConfig = {
    paid: { bg: 'bg-success/10', border: 'border-success', text: 'text-success' },
    pending: { bg: 'bg-warning/10', border: 'border-warning', text: 'text-warning' },
    overdue: { bg: 'bg-destructive/10', border: 'border-destructive', text: 'text-destructive' },
  }

  const statusStyle = statusConfig[status]

  return (
    <div
      className={cn(
        'border-3 border-foreground p-4 bg-card shadow-[4px_4px_0px_hsl(var(--shadow-color))] hover:shadow-[6px_6px_0px_hsl(var(--shadow-color))] hover:translate-x-[-2px] hover:translate-y-[-2px] transition-all',
        className
      )}
    >
      <div className="flex items-start justify-between mb-4">
        <div>
          <p className="font-black text-lg">{invoiceNumber}</p>
          <p className="text-sm text-muted-foreground">{clientName}</p>
        </div>
        <div
          className={cn(
            'px-2 py-1 text-xs font-bold uppercase border-2',
            statusStyle.bg,
            statusStyle.border,
            statusStyle.text
          )}
        >
          {status}
        </div>
      </div>

      <div className="grid grid-cols-2 gap-4 mb-4 text-sm">
        <div>
          <p className="text-xs font-bold uppercase text-muted-foreground">Issued</p>
          <p className="font-medium">{issueDate}</p>
        </div>
        <div>
          <p className="text-xs font-bold uppercase text-muted-foreground">Due</p>
          <p className="font-medium">{dueDate}</p>
        </div>
      </div>

      <div className="flex items-center justify-between">
        <p className="text-2xl font-black font-mono">${amount.toFixed(2)}</p>
        <div className="flex gap-2">
          {onDownload && (
            <Button variant="ghost" size="sm" onClick={onDownload}>
              <Download className="h-4 w-4" />
            </Button>
          )}
          {onView && (
            <Button size="sm" onClick={onView}>
              View
            </Button>
          )}
        </div>
      </div>
    </div>
  )
}

// ============================================================================
// INVOICE VARIANT 4: Invoice List
// ============================================================================
export interface InvoiceListItem {
  id: string
  invoiceNumber: string
  clientName: string
  date: string
  amount: number
  status: 'paid' | 'pending' | 'overdue'
}

export interface InvoiceListProps {
  invoices: InvoiceListItem[]
  onView?: (id: string) => void
  onDownload?: (id: string) => void
  className?: string
}

export function InvoiceList({
  invoices,
  onView,
  onDownload,
  className,
}: InvoiceListProps) {
  const statusConfig = {
    paid: 'bg-success text-success-foreground',
    pending: 'bg-warning text-warning-foreground',
    overdue: 'bg-destructive text-destructive-foreground',
  }

  return (
    <div className={cn('border-3 border-foreground bg-card', className)}>
      {/* Header */}
      <div className="grid grid-cols-12 gap-2 p-4 border-b-3 border-foreground bg-muted/50 font-bold uppercase text-xs">
        <div className="col-span-2">Invoice</div>
        <div className="col-span-3">Client</div>
        <div className="col-span-2">Date</div>
        <div className="col-span-2 text-right">Amount</div>
        <div className="col-span-2 text-right">Status</div>
        <div className="col-span-1" />
      </div>

      {/* Rows */}
      {invoices.map((invoice) => (
        <div
          key={invoice.id}
          className="grid grid-cols-12 gap-2 p-4 border-b border-foreground/20 hover:bg-muted/30 transition-colors items-center"
        >
          <div className="col-span-2 font-bold truncate">{invoice.invoiceNumber}</div>
          <div className="col-span-3 text-muted-foreground truncate">{invoice.clientName}</div>
          <div className="col-span-2 text-sm text-muted-foreground">{invoice.date}</div>
          <div className="col-span-2 text-right font-mono font-bold">
            ${invoice.amount.toFixed(2)}
          </div>
          <div className="col-span-2 flex justify-end">
            <span
              className={cn(
                'px-2 py-0.5 text-xs font-bold uppercase whitespace-nowrap',
                statusConfig[invoice.status]
              )}
            >
              {invoice.status}
            </span>
          </div>
          <div className="col-span-1 flex items-center justify-end gap-1">
            {onDownload && (
              <Button
                variant="ghost"
                size="sm"
                className="h-7 w-7 p-0"
                onClick={() => onDownload(invoice.id)}
              >
                <Download className="h-3 w-3" />
              </Button>
            )}
            {onView && (
              <Button
                variant="ghost"
                size="sm"
                className="h-7 w-7 p-0"
                onClick={() => onView(invoice.id)}
              >
                →
              </Button>
            )}
          </div>
        </div>
      ))}
    </div>
  )
}

// ============================================================================
// Helper Components
// ============================================================================
function AddressBlock({ address }: { address: InvoiceAddress }) {
  return (
    <div className="space-y-1 text-sm">
      <p className="font-bold">{address.name}</p>
      {address.company && <p>{address.company}</p>}
      <p className="text-muted-foreground">{address.address}</p>
      <p className="text-muted-foreground">
        {address.city}
        {address.state && `, ${address.state}`} {address.zip}
      </p>
      {address.country && <p className="text-muted-foreground">{address.country}</p>}
      {address.email && <p className="text-muted-foreground">{address.email}</p>}
      {address.phone && <p className="text-muted-foreground">{address.phone}</p>}
    </div>
  )
}

// ============================================================================
// Export all variants
// ============================================================================
export const InvoiceBlocks = {
  Full: Invoice,
  Receipt: Receipt,
  Summary: InvoiceSummary,
  List: InvoiceList,
}

// packages/vue/src/components/blocks/application/Invoice.vue
<script setup lang="ts">
import { computed } from 'vue'
import { cn } from '@/lib/utils'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui'
import Button from '@/components/ui/Button.vue'
import Separator from '@/components/ui/Separator.vue'
import Badge from '@/components/ui/Badge.vue'
import { Download, Printer, Mail, FileText, CheckCircle, Clock, AlertCircle } from 'lucide-vue-next'

type InvoiceVariant = 'full' | 'receipt' | 'summary' | 'list'
type InvoiceStatus = 'paid' | 'pending' | 'overdue'

interface InvoiceItem {
  description: string
  quantity: number
  unitPrice: number
  total: number
}

interface InvoiceData {
  id: string
  status: InvoiceStatus
  date: string
  dueDate?: string
  from: {
    name: string
    address?: string
    email?: string
    phone?: string
  }
  to: {
    name: string
    address?: string
    email?: string
  }
  items: InvoiceItem[]
  subtotal: number
  tax?: number
  taxRate?: number
  discount?: number
  total: number
}

interface InvoiceProps {
  variant?: InvoiceVariant
  invoice: InvoiceData
  invoices?: InvoiceData[]
  class?: string
}

const props = withDefaults(defineProps<InvoiceProps>(), {
  variant: 'full',
})

const emit = defineEmits<{
  (e: 'download', id: string): void
  (e: 'print', id: string): void
  (e: 'send', id: string): void
  (e: 'viewDetails', id: string): void
}>()

const formatCurrency = (amount: number) => {
  return new Intl.NumberFormat('en-US', {
    style: 'currency',
    currency: 'USD',
  }).format(amount)
}

const statusConfig = {
  paid: { label: 'Paid', variant: 'success' as const, icon: CheckCircle },
  pending: { label: 'Pending', variant: 'warning' as const, icon: Clock },
  overdue: { label: 'Overdue', variant: 'destructive' as const, icon: AlertCircle },
}
</script>

<template>
  <!-- Full Invoice -->
  <div v-if="variant === 'full'" :class="cn('max-w-3xl mx-auto p-6', props.class)">
    <Card class="shadow-[8px_8px_0px_hsl(var(--shadow-color))]">
      <CardHeader class="flex flex-row items-start justify-between">
        <div>
          <CardTitle class="text-3xl uppercase">Invoice</CardTitle>
          <p class="text-muted-foreground font-mono mt-1">#{{ invoice.id }}</p>
        </div>
        <Badge :variant="statusConfig[invoice.status].variant" class="gap-1.5">
          <component :is="statusConfig[invoice.status].icon" class="h-3.5 w-3.5" />
          {{ statusConfig[invoice.status].label }}
        </Badge>
      </CardHeader>
      <CardContent class="space-y-8">
        <div class="grid md:grid-cols-2 gap-8">
          <div>
            <p class="font-bold uppercase text-sm text-muted-foreground mb-2">From</p>
            <p class="font-bold text-lg">{{ invoice.from.name }}</p>
            <p v-if="invoice.from.address" class="text-muted-foreground">{{ invoice.from.address }}</p>
            <p v-if="invoice.from.email" class="text-muted-foreground">{{ invoice.from.email }}</p>
            <p v-if="invoice.from.phone" class="text-muted-foreground">{{ invoice.from.phone }}</p>
          </div>
          <div>
            <p class="font-bold uppercase text-sm text-muted-foreground mb-2">Bill To</p>
            <p class="font-bold text-lg">{{ invoice.to.name }}</p>
            <p v-if="invoice.to.address" class="text-muted-foreground">{{ invoice.to.address }}</p>
            <p v-if="invoice.to.email" class="text-muted-foreground">{{ invoice.to.email }}</p>
          </div>
        </div>

        <div class="grid grid-cols-2 gap-4 text-sm">
          <div class="border-3 border-foreground p-4">
            <p class="font-bold uppercase text-muted-foreground">Invoice Date</p>
            <p class="font-bold text-lg">{{ invoice.date }}</p>
          </div>
          <div v-if="invoice.dueDate" class="border-3 border-foreground p-4">
            <p class="font-bold uppercase text-muted-foreground">Due Date</p>
            <p class="font-bold text-lg">{{ invoice.dueDate }}</p>
          </div>
        </div>

        <div class="border-3 border-foreground">
          <table class="w-full">
            <thead>
              <tr class="border-b-3 border-foreground bg-muted">
                <th class="text-left p-4 font-bold uppercase text-sm">Description</th>
                <th class="text-right p-4 font-bold uppercase text-sm">Qty</th>
                <th class="text-right p-4 font-bold uppercase text-sm">Price</th>
                <th class="text-right p-4 font-bold uppercase text-sm">Total</th>
              </tr>
            </thead>
            <tbody>
              <tr v-for="item in invoice.items" :key="item.description" class="border-b border-foreground/20">
                <td class="p-4">{{ item.description }}</td>
                <td class="p-4 text-right">{{ item.quantity }}</td>
                <td class="p-4 text-right">{{ formatCurrency(item.unitPrice) }}</td>
                <td class="p-4 text-right font-bold">{{ formatCurrency(item.total) }}</td>
              </tr>
            </tbody>
          </table>
        </div>

        <div class="flex justify-end">
          <div class="w-64 space-y-2">
            <div class="flex justify-between">
              <span class="text-muted-foreground">Subtotal</span>
              <span>{{ formatCurrency(invoice.subtotal) }}</span>
            </div>
            <div v-if="invoice.tax" class="flex justify-between">
              <span class="text-muted-foreground">Tax ({{ invoice.taxRate }}%)</span>
              <span>{{ formatCurrency(invoice.tax) }}</span>
            </div>
            <div v-if="invoice.discount" class="flex justify-between text-success">
              <span>Discount</span>
              <span>-{{ formatCurrency(invoice.discount) }}</span>
            </div>
            <Separator class="bg-foreground h-[3px]" />
            <div class="flex justify-between font-black text-lg">
              <span class="uppercase">Total</span>
              <span>{{ formatCurrency(invoice.total) }}</span>
            </div>
          </div>
        </div>

        <div class="flex gap-3 justify-end pt-4">
          <Button variant="outline" class="gap-2" @click="emit('download', invoice.id)">
            <Download class="h-4 w-4" />
            Download
          </Button>
          <Button variant="outline" class="gap-2" @click="emit('print', invoice.id)">
            <Printer class="h-4 w-4" />
            Print
          </Button>
          <Button class="gap-2" @click="emit('send', invoice.id)">
            <Mail class="h-4 w-4" />
            Send
          </Button>
        </div>
      </CardContent>
    </Card>
  </div>

  <!-- Receipt Variant -->
  <div v-else-if="variant === 'receipt'" :class="cn('max-w-sm mx-auto p-6', props.class)">
    <Card class="shadow-[6px_6px_0px_hsl(var(--shadow-color))]">
      <CardContent class="pt-6 text-center">
        <div class="w-16 h-16 mx-auto border-3 border-foreground bg-success flex items-center justify-center mb-4 shadow-[4px_4px_0px_hsl(var(--shadow-color))]">
          <CheckCircle class="h-8 w-8 text-success-foreground" />
        </div>
        <h2 class="text-2xl font-black uppercase mb-2">Payment Received</h2>
        <p class="text-muted-foreground mb-6">Thank you for your purchase!</p>

        <div class="border-3 border-foreground p-4 mb-6 text-left">
          <div class="flex justify-between mb-2">
            <span class="text-muted-foreground">Receipt #</span>
            <span class="font-mono font-bold">{{ invoice.id }}</span>
          </div>
          <div class="flex justify-between mb-2">
            <span class="text-muted-foreground">Date</span>
            <span class="font-bold">{{ invoice.date }}</span>
          </div>
          <Separator class="bg-foreground/20 my-3" />
          <div v-for="item in invoice.items" :key="item.description" class="flex justify-between mb-1">
            <span>{{ item.description }}</span>
            <span class="font-bold">{{ formatCurrency(item.total) }}</span>
          </div>
          <Separator class="bg-foreground h-[2px] my-3" />
          <div class="flex justify-between font-black text-lg">
            <span class="uppercase">Total</span>
            <span>{{ formatCurrency(invoice.total) }}</span>
          </div>
        </div>

        <Button class="w-full gap-2" @click="emit('download', invoice.id)">
          <Download class="h-4 w-4" />
          Download Receipt
        </Button>
      </CardContent>
    </Card>
  </div>

  <!-- Summary Variant -->
  <div v-else-if="variant === 'summary'" :class="cn('max-w-md mx-auto p-6', props.class)">
    <Card class="shadow-[6px_6px_0px_hsl(var(--shadow-color))]">
      <CardHeader class="flex flex-row items-center justify-between">
        <div>
          <CardTitle class="uppercase">Invoice Summary</CardTitle>
          <p class="text-sm text-muted-foreground font-mono">#{{ invoice.id }}</p>
        </div>
        <Badge :variant="statusConfig[invoice.status].variant">
          {{ statusConfig[invoice.status].label }}
        </Badge>
      </CardHeader>
      <CardContent class="space-y-4">
        <div class="flex justify-between">
          <span class="text-muted-foreground">To</span>
          <span class="font-bold">{{ invoice.to.name }}</span>
        </div>
        <div class="flex justify-between">
          <span class="text-muted-foreground">Date</span>
          <span>{{ invoice.date }}</span>
        </div>
        <div v-if="invoice.dueDate" class="flex justify-between">
          <span class="text-muted-foreground">Due Date</span>
          <span>{{ invoice.dueDate }}</span>
        </div>
        <Separator class="bg-foreground h-[2px]" />
        <div class="flex justify-between font-black text-xl">
          <span class="uppercase">Total</span>
          <span>{{ formatCurrency(invoice.total) }}</span>
        </div>
        <Button class="w-full gap-2" @click="emit('viewDetails', invoice.id)">
          <FileText class="h-4 w-4" />
          View Details
        </Button>
      </CardContent>
    </Card>
  </div>

  <!-- List Variant -->
  <div v-else-if="variant === 'list'" :class="cn('max-w-4xl mx-auto p-6', props.class)">
    <Card class="shadow-[8px_8px_0px_hsl(var(--shadow-color))]">
      <CardHeader>
        <CardTitle class="uppercase">Invoices</CardTitle>
      </CardHeader>
      <CardContent>
        <div class="border-3 border-foreground">
          <table class="w-full">
            <thead>
              <tr class="border-b-3 border-foreground bg-muted">
                <th class="text-left p-4 font-bold uppercase text-sm">Invoice</th>
                <th class="text-left p-4 font-bold uppercase text-sm">Client</th>
                <th class="text-left p-4 font-bold uppercase text-sm">Date</th>
                <th class="text-left p-4 font-bold uppercase text-sm">Status</th>
                <th class="text-right p-4 font-bold uppercase text-sm">Amount</th>
                <th class="text-right p-4 font-bold uppercase text-sm">Actions</th>
              </tr>
            </thead>
            <tbody>
              <tr
                v-for="inv in (invoices || [invoice])"
                :key="inv.id"
                class="border-b border-foreground/20 hover:bg-muted/50"
              >
                <td class="p-4 font-mono font-bold">#{{ inv.id }}</td>
                <td class="p-4">{{ inv.to.name }}</td>
                <td class="p-4">{{ inv.date }}</td>
                <td class="p-4">
                  <Badge :variant="statusConfig[inv.status].variant" class="gap-1">
                    <component :is="statusConfig[inv.status].icon" class="h-3 w-3" />
                    {{ statusConfig[inv.status].label }}
                  </Badge>
                </td>
                <td class="p-4 text-right font-bold">{{ formatCurrency(inv.total) }}</td>
                <td class="p-4 text-right">
                  <div class="flex gap-2 justify-end">
                    <Button size="sm" variant="ghost" @click="emit('viewDetails', inv.id)">
                      View
                    </Button>
                    <Button size="sm" variant="outline" @click="emit('download', inv.id)">
                      <Download class="h-4 w-4" />
                    </Button>
                  </div>
                </td>
              </tr>
            </tbody>
          </table>
        </div>
      </CardContent>
    </Card>
  </div>
</template>
