// packages/vue/src/components/ui/DonutChart.vue
<script setup lang="ts">
import { computed } from 'vue'
import { use } from 'echarts/core'
import { CanvasRenderer } from 'echarts/renderers'
import { PieChart } from 'echarts/charts'
import { TooltipComponent, LegendComponent } from 'echarts/components'
import VChart from 'vue-echarts'
import { cn } from '@/lib/utils'
import { neubrutalismTheme, type ChartConfig } from './chart-utils'
import { chartContainerVariants } from './chart-variants'
import ChartEmpty from './ChartEmpty.vue'
import type { VariantProps } from 'class-variance-authority'

// Register ECharts components
use([CanvasRenderer, PieChart, TooltipComponent, LegendComponent])

type ChartVariants = VariantProps<typeof chartContainerVariants>

interface DonutChartData {
  name: string
  value: number
  fill?: string
}

interface DonutChartProps {
  data: DonutChartData[]
  config: ChartConfig
  innerRadius?: string
  outerRadius?: string
  showLabels?: 'none' | 'inside' | 'outside'
  showLegend?: boolean
  height?: string
  variant?: ChartVariants['variant']
  class?: string
  emptyMessage?: string
}

const props = withDefaults(defineProps<DonutChartProps>(), {
  innerRadius: '60%',
  outerRadius: '80%',
  showLabels: 'none',
  showLegend: false,
  height: '300px',
  variant: 'default',
})

const isEmpty = computed(() => !props.data || props.data.length === 0)

const option = computed(() => ({
  tooltip: {
    trigger: 'item',
    formatter: '{b}: {c} ({d}%)',
  },
  legend: props.showLegend ? {
    orient: 'horizontal',
    bottom: 0,
    textStyle: {
      fontWeight: 'bold',
    },
  } : undefined,
  series: [{
    type: 'pie',
    radius: [props.innerRadius, props.outerRadius],
    center: ['50%', '50%'],
    avoidLabelOverlap: true,
    itemStyle: {
      borderColor: 'hsl(var(--foreground))',
      borderWidth: 3,
    },
    label: props.showLabels === 'none' ? { show: false } : {
      show: true,
      position: props.showLabels,
      fontWeight: 'bold',
      formatter: '{b}',
    },
    labelLine: {
      show: props.showLabels === 'outside',
    },
    data: props.data.map(item => ({
      name: item.name,
      value: item.value,
      itemStyle: item.fill ? { color: item.fill } : undefined,
    })),
  }],
}))
</script>

<template>
  <div
    data-slot="chart"
    :class="cn(chartContainerVariants({ variant }), props.class)"
  >
    <ChartEmpty v-if="isEmpty" :message="emptyMessage" />
    <div v-else class="relative" :style="{ height }">
      <VChart
        :option="option"
        :theme="neubrutalismTheme"
        :autoresize="true"
        style="width: 100%; height: 100%"
      />
      <!-- Center content slot -->
      <div
        v-if="$slots.default"
        class="absolute inset-0 flex items-center justify-center pointer-events-none"
      >
        <slot />
      </div>
    </div>
  </div>
</template>

// src/components/ui/chart/donut-chart.tsx
import * as React from 'react'
import { cn } from '@/lib/utils'
import { Pie, PieChart, Cell, Label } from 'recharts'
import { ChartContainer } from './container'
import { ChartEmpty } from './empty'
import { ChartTooltip, ChartTooltipContent } from './tooltip'
import type { ChartConfig } from './types'

export interface DonutChartData {
  name: string
  value: number
  fill?: string
}

export interface DonutChartProps extends React.HTMLAttributes<HTMLDivElement> {
  data: DonutChartData[]
  config: ChartConfig
  innerRadius?: string | number
  outerRadius?: string | number
  centerContent?: React.ReactNode
  showLabels?: 'none' | 'inside' | 'outside'
  variant?: 'default' | 'separated'
  showTooltip?: boolean
  animated?: boolean
  emptyState?: React.ReactNode
}

const DonutChart = React.forwardRef<HTMLDivElement, DonutChartProps>(
  (
    {
      data,
      config,
      innerRadius = '60%',
      outerRadius = '80%',
      centerContent,
      showLabels = 'none',
      variant = 'default',
      showTooltip = true,
      animated = true,
      emptyState,
      className,
      ...props
    },
    ref
  ) => {
    if (!data || data.length === 0) {
      return <ChartEmpty ref={ref} message={emptyState} className={className} {...props} />
    }

    const paddingAngle = variant === 'separated' ? 4 : 0

    // Calculate total for center content (available for custom center content)
    const _total = React.useMemo(
      () => data.reduce((sum, item) => sum + item.value, 0),
      [data]
    )
    void _total // Used by consumer via centerContent prop

    return (
      <ChartContainer
        ref={ref}
        config={config}
        className={cn('aspect-square max-h-[300px]', className)}
        {...props}
      >
        <PieChart>
          {showTooltip && (
            <ChartTooltip
              cursor={false}
              content={<ChartTooltipContent hideLabel />}
            />
          )}
          <Pie
            data={data}
            dataKey="value"
            nameKey="name"
            cx="50%"
            cy="50%"
            innerRadius={innerRadius}
            outerRadius={outerRadius}
            paddingAngle={paddingAngle}
            strokeWidth={3}
            stroke="hsl(var(--foreground))"
            isAnimationActive={animated}
            animationDuration={400}
            label={
              showLabels === 'outside'
                ? ({ name, percent }: { name?: string; percent?: number }) => `${name ?? ''}: ${((percent ?? 0) * 100).toFixed(0)}%`
                : showLabels === 'inside'
                ? ({ percent }: { percent?: number }) => `${((percent ?? 0) * 100).toFixed(0)}%`
                : false
            }
            labelLine={showLabels === 'outside'}
          >
            {data.map((entry, index) => (
              <Cell
                key={`cell-${index}`}
                fill={entry.fill || `hsl(var(--chart-${(index % 5) + 1}))`}
              />
            ))}
            {centerContent && (
              <Label
                content={({ viewBox }) => {
                  if (viewBox && 'cx' in viewBox && 'cy' in viewBox) {
                    const pieView = viewBox as { cx: number; cy: number; innerRadius?: number; outerRadius?: number }
                    const ir = pieView.innerRadius ?? (typeof innerRadius === 'number' ? innerRadius : 60)
                    const fwHalf = Math.max(40, ir * 0.85)
                    const fhHalf = Math.max(25, ir * 0.55)
                    return (
                      <foreignObject
                        x={(pieView.cx || 0) - fwHalf}
                        y={(pieView.cy || 0) - fhHalf}
                        width={fwHalf * 2}
                        height={fhHalf * 2}
                      >
                        <div className="flex h-full w-full items-center justify-center">
                          {centerContent}
                        </div>
                      </foreignObject>
                    )
                  }
                  return null
                }}
              />
            )}
          </Pie>
        </PieChart>
      </ChartContainer>
    )
  }
)
DonutChart.displayName = 'DonutChart'

// Helper component for common center content pattern
export interface DonutChartCenterProps {
  value: string | number
  label?: string
  className?: string
}

const DonutChartCenter = React.forwardRef<HTMLDivElement, DonutChartCenterProps>(
  ({ value, label, className }, ref) => {
    return (
      <div ref={ref} className={cn('text-center', className)}>
        <div className="text-2xl font-black">{value}</div>
        {label && (
          <div className="text-xs font-bold uppercase tracking-wide text-muted-foreground">
            {label}
          </div>
        )}
      </div>
    )
  }
)
DonutChartCenter.displayName = 'DonutChartCenter'

export { DonutChart, DonutChartCenter }
