// packages/vue/src/components/ui/TreemapChart.vue
<script setup lang="ts">
import { computed } from 'vue'
import { use } from 'echarts/core'
import { CanvasRenderer } from 'echarts/renderers'
import { TreemapChart as EChartsTreemap } from 'echarts/charts'
import { TooltipComponent } from 'echarts/components'
import VChart from 'vue-echarts'
import { cn } from '@/lib/utils'
import { neubrutalismTheme } from './chart-utils'
import ChartEmpty from './ChartEmpty.vue'

use([CanvasRenderer, EChartsTreemap, TooltipComponent])

export interface TreemapChartData {
  name: string
  value?: number
  children?: TreemapChartData[]
}

interface Props {
  data: TreemapChartData[]
  showTooltip?: boolean
  animated?: boolean
  height?: string
  class?: string
  emptyMessage?: string
}

const props = withDefaults(defineProps<Props>(), {
  showTooltip: true,
  animated: true,
  height: '320px',
})

const COLORS = [
  'hsl(var(--primary))',
  'hsl(var(--secondary))',
  'hsl(var(--accent))',
  'hsl(var(--success))',
  'hsl(var(--info))',
  'hsl(var(--warning))',
]

const isEmpty = computed(() => !props.data || props.data.length === 0)

const option = computed(() => ({
  tooltip: props.showTooltip ? {
    trigger: 'item',
    formatter: (params: { name: string; value: number }) =>
      `${params.name}: ${params.value?.toLocaleString() ?? ''}`,
    backgroundColor: 'hsl(var(--background))',
    borderColor: 'hsl(var(--foreground))',
    borderWidth: 3,
    padding: [6, 10],
    textStyle: {
      color: 'hsl(var(--foreground))',
      fontFamily: "'DM Mono', monospace",
      fontSize: 12,
    },
    extraCssText: 'border-radius: 0; box-shadow: 4px 4px 0px hsl(var(--foreground));',
  } : undefined,
  series: [{
    type: 'treemap',
    animation: props.animated,
    animationDuration: 400,
    itemStyle: {
      borderColor: 'hsl(var(--foreground))',
      borderWidth: 3,
      gapWidth: 4,
    },
    label: {
      show: true,
      fontWeight: 'bold',
      fontFamily: 'inherit',
      fontSize: 13,
      color: 'hsl(var(--foreground))',
    },
    upperLabel: {
      show: false,
    },
    levels: [
      {
        colorSaturation: [0.7, 1],
        itemStyle: {
          borderWidth: 3,
          borderColor: 'hsl(var(--foreground))',
          gapWidth: 4,
        },
      },
    ],
    data: props.data.map((d, i) => ({
      ...d,
      itemStyle: { color: COLORS[i % COLORS.length] },
    })),
  }],
}))
</script>

<template>
  <div :class="cn('w-full', props.class)" :style="{ height }">
    <ChartEmpty v-if="isEmpty" :message="emptyMessage" />
    <VChart
      v-else
      :option="option"
      :theme="neubrutalismTheme"
      :autoresize="true"
      style="width: 100%; height: 100%"
    />
  </div>
</template>

// src/components/ui/chart/treemap-chart.tsx
import * as React from 'react'
import { cn } from '@/lib/utils'
import { Treemap as RechartsTreemap, ResponsiveContainer, Tooltip } from 'recharts'
import { ChartEmpty } from './empty'

export interface TreemapChartData {
  name: string
  value?: number
  children?: TreemapChartData[]
  fill?: string
  [key: string]: unknown
}

export interface TreemapChartProps extends React.HTMLAttributes<HTMLDivElement> {
  data: TreemapChartData[]
  showTooltip?: boolean
  animated?: boolean
  height?: number
  /** Accessible label for screen readers (default: "Treemap chart") */
  ariaLabel?: string
  emptyState?: React.ReactNode
}

const NEUBRUTALISM_COLORS = [
  'hsl(var(--primary))',
  'hsl(var(--secondary))',
  'hsl(var(--accent))',
  'hsl(var(--success))',
  'hsl(var(--info))',
  'hsl(var(--warning))',
]

interface CustomContentProps {
  x?: number
  y?: number
  width?: number
  height?: number
  name?: string
  value?: number
  depth?: number
  index?: number
}

function CustomTreemapContent(props: CustomContentProps) {
  const { x = 0, y = 0, width = 0, height = 0, name, value, depth = 0, index = 0 } = props
  const colorIndex = (depth * 7 + index) % NEUBRUTALISM_COLORS.length
  const fill = NEUBRUTALISM_COLORS[colorIndex]
  const isSmall = width < 60 || height < 40

  if (depth === 0) return null

  return (
    <g>
      <rect
        x={x + 2}
        y={y + 2}
        width={width - 4}
        height={height - 4}
        style={{ fill, stroke: 'hsl(var(--foreground))', strokeWidth: 3 }}
      />
      {!isSmall && (
        <>
          <text
            x={x + width / 2}
            y={y + height / 2 - (value !== undefined ? 8 : 0)}
            textAnchor="middle"
            dominantBaseline="central"
            fill="hsl(var(--foreground))"
            style={{ fontFamily: 'inherit', fontSize: Math.min(14, width / 6), fontWeight: 900 }}
          >
            {name}
          </text>
          {value !== undefined && (
            <text
              x={x + width / 2}
              y={y + height / 2 + 10}
              textAnchor="middle"
              dominantBaseline="central"
              fill="hsl(var(--foreground))"
              style={{ fontFamily: "'DM Mono', monospace", fontSize: Math.min(11, width / 8), fontWeight: 700, opacity: 0.75 }}
            >
              {value.toLocaleString()}
            </text>
          )}
        </>
      )}
    </g>
  )
}

const TreemapChart = React.forwardRef<HTMLDivElement, TreemapChartProps>(
  (
    {
      data,
      showTooltip = true,
      animated = true,
      height = 320,
      ariaLabel = 'Treemap chart',
      emptyState,
      className,
      ...props
    },
    ref
  ) => {
    if (!data || data.length === 0) {
      return <ChartEmpty ref={ref} message={emptyState} className={className} {...props} />
    }

    return (
      <div
        ref={ref}
        role="img"
        aria-label={ariaLabel}
        className={cn('w-full', className)}
        style={{ height }}
        {...props}
      >
        <ResponsiveContainer width="100%" height="100%">
          <RechartsTreemap
            data={data}
            dataKey="value"
            aspectRatio={4 / 3}
            isAnimationActive={animated}
            animationDuration={400}
            content={<CustomTreemapContent />}
          >
            {showTooltip && (
              <Tooltip
                contentStyle={{
                  border: '3px solid hsl(var(--foreground))',
                  borderRadius: 0,
                  boxShadow: '4px 4px 0px hsl(var(--foreground))',
                  background: 'hsl(var(--background))',
                  fontFamily: "'DM Mono', monospace",
                  fontSize: 12,
                }}
                formatter={(value, name) => [
                  typeof value === 'number' ? value.toLocaleString() : String(value ?? ''),
                  String(name ?? ''),
                ]}
              />
            )}
          </RechartsTreemap>
        </ResponsiveContainer>
      </div>
    )
  }
)
TreemapChart.displayName = 'TreemapChart'

export { TreemapChart }
