// packages/vue/src/components/blocks/marketing/ContactSection.vue
<script setup lang="ts">
import { ref } from 'vue'
import { cn } from '@/lib/utils'
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui'
import Button from '@/components/ui/Button.vue'
import Input from '@/components/ui/Input.vue'
import Textarea from '@/components/ui/Textarea.vue'
import Label from '@/components/ui/Label.vue'
import { Mail, Phone, MapPin, Send, Clock, MessageCircle } from 'lucide-vue-next'

type ContactVariant = 'split' | 'centered' | 'withCards' | 'withMap'

interface ContactInfo {
  email?: string
  phone?: string
  address?: string
  hours?: string
}

interface ContactSectionProps {
  variant?: ContactVariant
  title?: string
  subtitle?: string
  description?: string
  contactInfo?: ContactInfo
  mapEmbedUrl?: string
  class?: string
}

const props = withDefaults(defineProps<ContactSectionProps>(), {
  variant: 'split',
})

const emit = defineEmits<{
  (e: 'submit', data: { name: string; email: string; message: string }): void
}>()

const name = ref('')
const email = ref('')
const message = ref('')

const handleSubmit = () => {
  emit('submit', {
    name: name.value,
    email: email.value,
    message: message.value,
  })
  name.value = ''
  email.value = ''
  message.value = ''
}
</script>

<template>
  <!-- Split Variant -->
  <section
    v-if="variant === 'split'"
    :class="cn('py-16 px-4 md:px-8 lg:px-16', props.class)"
  >
    <div class="max-w-6xl mx-auto">
      <div class="grid lg:grid-cols-2 gap-12">
        <div class="space-y-8">
          <div>
            <p v-if="subtitle" class="text-sm font-bold uppercase tracking-widest text-primary mb-2">
              {{ subtitle }}
            </p>
            <h2 v-if="title" class="text-3xl md:text-4xl font-black uppercase tracking-tight mb-4">
              {{ title }}
            </h2>
            <p v-if="description" class="text-lg text-muted-foreground font-medium">
              {{ description }}
            </p>
          </div>

          <div v-if="contactInfo" class="space-y-4">
            <div v-if="contactInfo.email" class="flex items-center gap-4">
              <div class="w-12 h-12 flex items-center justify-center border-3 border-foreground bg-primary shadow-[3px_3px_0px_hsl(var(--shadow-color))]">
                <Mail class="h-5 w-5 text-primary-foreground" />
              </div>
              <div>
                <p class="font-bold text-sm uppercase">Email</p>
                <a :href="`mailto:${contactInfo.email}`" class="text-muted-foreground hover:text-foreground">
                  {{ contactInfo.email }}
                </a>
              </div>
            </div>

            <div v-if="contactInfo.phone" class="flex items-center gap-4">
              <div class="w-12 h-12 flex items-center justify-center border-3 border-foreground bg-secondary shadow-[3px_3px_0px_hsl(var(--shadow-color))]">
                <Phone class="h-5 w-5 text-secondary-foreground" />
              </div>
              <div>
                <p class="font-bold text-sm uppercase">Phone</p>
                <a :href="`tel:${contactInfo.phone}`" class="text-muted-foreground hover:text-foreground">
                  {{ contactInfo.phone }}
                </a>
              </div>
            </div>

            <div v-if="contactInfo.address" class="flex items-center gap-4">
              <div class="w-12 h-12 flex items-center justify-center border-3 border-foreground bg-accent shadow-[3px_3px_0px_hsl(var(--shadow-color))]">
                <MapPin class="h-5 w-5 text-accent-foreground" />
              </div>
              <div>
                <p class="font-bold text-sm uppercase">Address</p>
                <p class="text-muted-foreground">{{ contactInfo.address }}</p>
              </div>
            </div>

            <div v-if="contactInfo.hours" class="flex items-center gap-4">
              <div class="w-12 h-12 flex items-center justify-center border-3 border-foreground bg-success shadow-[3px_3px_0px_hsl(var(--shadow-color))]">
                <Clock class="h-5 w-5 text-success-foreground" />
              </div>
              <div>
                <p class="font-bold text-sm uppercase">Hours</p>
                <p class="text-muted-foreground">{{ contactInfo.hours }}</p>
              </div>
            </div>
          </div>
        </div>

        <Card class="shadow-[8px_8px_0px_hsl(var(--shadow-color))]">
          <CardHeader>
            <CardTitle class="uppercase">Send us a message</CardTitle>
            <CardDescription>Fill out the form and we'll get back to you.</CardDescription>
          </CardHeader>
          <CardContent>
            <form class="space-y-4" @submit.prevent="handleSubmit">
              <div class="space-y-2">
                <Label for="name">Name</Label>
                <Input id="name" v-model="name" placeholder="Your name" required />
              </div>
              <div class="space-y-2">
                <Label for="email">Email</Label>
                <Input id="email" v-model="email" type="email" placeholder="your@email.com" required />
              </div>
              <div class="space-y-2">
                <Label for="message">Message</Label>
                <Textarea id="message" v-model="message" placeholder="How can we help?" rows="4" required />
              </div>
              <Button type="submit" class="w-full">
                Send Message
                <Send class="ml-2 h-4 w-4" />
              </Button>
            </form>
          </CardContent>
        </Card>
      </div>
    </div>
  </section>

  <!-- Centered Variant -->
  <section
    v-else-if="variant === 'centered'"
    :class="cn('py-16 px-4 md:px-8 lg:px-16', props.class)"
  >
    <div class="max-w-2xl mx-auto">
      <div v-if="title || subtitle || description" class="text-center mb-12 space-y-4">
        <p v-if="subtitle" class="text-sm font-bold uppercase tracking-widest text-primary">
          {{ subtitle }}
        </p>
        <h2 v-if="title" class="text-3xl md:text-4xl font-black uppercase tracking-tight">
          {{ title }}
        </h2>
        <p v-if="description" class="text-lg text-muted-foreground font-medium">
          {{ description }}
        </p>
      </div>

      <Card class="shadow-[8px_8px_0px_hsl(var(--shadow-color))]">
        <CardContent class="pt-6">
          <form class="space-y-4" @submit.prevent="handleSubmit">
            <div class="grid md:grid-cols-2 gap-4">
              <div class="space-y-2">
                <Label for="name-centered">Name</Label>
                <Input id="name-centered" v-model="name" placeholder="Your name" required />
              </div>
              <div class="space-y-2">
                <Label for="email-centered">Email</Label>
                <Input id="email-centered" v-model="email" type="email" placeholder="your@email.com" required />
              </div>
            </div>
            <div class="space-y-2">
              <Label for="message-centered">Message</Label>
              <Textarea id="message-centered" v-model="message" placeholder="How can we help?" rows="6" required />
            </div>
            <Button type="submit" class="w-full" size="lg">
              Send Message
              <Send class="ml-2 h-4 w-4" />
            </Button>
          </form>
        </CardContent>
      </Card>
    </div>
  </section>

  <!-- WithCards Variant -->
  <section
    v-else-if="variant === 'withCards'"
    :class="cn('py-16 px-4 md:px-8 lg:px-16 bg-muted/30', props.class)"
  >
    <div class="max-w-6xl mx-auto">
      <div v-if="title || subtitle" class="text-center mb-12 space-y-4">
        <p v-if="subtitle" class="text-sm font-bold uppercase tracking-widest text-secondary">
          {{ subtitle }}
        </p>
        <h2 v-if="title" class="text-3xl md:text-4xl font-black uppercase tracking-tight">
          {{ title }}
        </h2>
      </div>

      <div class="grid md:grid-cols-3 gap-6 mb-12">
        <Card v-if="contactInfo?.email" class="text-center hover:translate-y-[-4px] hover:shadow-[8px_8px_0px_hsl(var(--shadow-color))] transition-all">
          <CardContent class="pt-6">
            <div class="w-16 h-16 mx-auto flex items-center justify-center border-3 border-foreground bg-primary mb-4 shadow-[4px_4px_0px_hsl(var(--shadow-color))]">
              <Mail class="h-7 w-7 text-primary-foreground" />
            </div>
            <h3 class="font-bold uppercase mb-2">Email Us</h3>
            <a :href="`mailto:${contactInfo.email}`" class="text-muted-foreground hover:text-foreground">
              {{ contactInfo.email }}
            </a>
          </CardContent>
        </Card>

        <Card v-if="contactInfo?.phone" class="text-center hover:translate-y-[-4px] hover:shadow-[8px_8px_0px_hsl(var(--shadow-color))] transition-all">
          <CardContent class="pt-6">
            <div class="w-16 h-16 mx-auto flex items-center justify-center border-3 border-foreground bg-secondary mb-4 shadow-[4px_4px_0px_hsl(var(--shadow-color))]">
              <Phone class="h-7 w-7 text-secondary-foreground" />
            </div>
            <h3 class="font-bold uppercase mb-2">Call Us</h3>
            <a :href="`tel:${contactInfo.phone}`" class="text-muted-foreground hover:text-foreground">
              {{ contactInfo.phone }}
            </a>
          </CardContent>
        </Card>

        <Card class="text-center hover:translate-y-[-4px] hover:shadow-[8px_8px_0px_hsl(var(--shadow-color))] transition-all">
          <CardContent class="pt-6">
            <div class="w-16 h-16 mx-auto flex items-center justify-center border-3 border-foreground bg-accent mb-4 shadow-[4px_4px_0px_hsl(var(--shadow-color))]">
              <MessageCircle class="h-7 w-7 text-accent-foreground" />
            </div>
            <h3 class="font-bold uppercase mb-2">Live Chat</h3>
            <p class="text-muted-foreground">Available 24/7</p>
          </CardContent>
        </Card>
      </div>

      <Card class="max-w-2xl mx-auto shadow-[8px_8px_0px_hsl(var(--shadow-color))]">
        <CardHeader>
          <CardTitle class="uppercase text-center">Send a Message</CardTitle>
        </CardHeader>
        <CardContent>
          <form class="space-y-4" @submit.prevent="handleSubmit">
            <div class="grid md:grid-cols-2 gap-4">
              <div class="space-y-2">
                <Label for="name-cards">Name</Label>
                <Input id="name-cards" v-model="name" placeholder="Your name" required />
              </div>
              <div class="space-y-2">
                <Label for="email-cards">Email</Label>
                <Input id="email-cards" v-model="email" type="email" placeholder="your@email.com" required />
              </div>
            </div>
            <div class="space-y-2">
              <Label for="message-cards">Message</Label>
              <Textarea id="message-cards" v-model="message" placeholder="How can we help?" rows="4" required />
            </div>
            <Button type="submit" class="w-full">
              Send Message
              <Send class="ml-2 h-4 w-4" />
            </Button>
          </form>
        </CardContent>
      </Card>
    </div>
  </section>

  <!-- WithMap Variant -->
  <section
    v-else-if="variant === 'withMap'"
    :class="cn('py-16 px-4 md:px-8 lg:px-16', props.class)"
  >
    <div class="max-w-7xl mx-auto">
      <div v-if="title || subtitle" class="text-center mb-12 space-y-4">
        <p v-if="subtitle" class="text-sm font-bold uppercase tracking-widest text-accent">
          {{ subtitle }}
        </p>
        <h2 v-if="title" class="text-3xl md:text-4xl font-black uppercase tracking-tight">
          {{ title }}
        </h2>
      </div>

      <div class="grid lg:grid-cols-2 gap-8">
        <div class="border-3 border-foreground shadow-[6px_6px_0px_hsl(var(--shadow-color))] overflow-hidden h-[400px]">
          <iframe
            v-if="mapEmbedUrl"
            :src="mapEmbedUrl"
            width="100%"
            height="100%"
            style="border: 0"
            allowfullscreen
            loading="lazy"
          />
          <div v-else class="w-full h-full bg-muted flex items-center justify-center">
            <MapPin class="h-12 w-12 text-muted-foreground" />
          </div>
        </div>

        <Card class="shadow-[8px_8px_0px_hsl(var(--shadow-color))]">
          <CardHeader>
            <CardTitle class="uppercase">Get in Touch</CardTitle>
          </CardHeader>
          <CardContent>
            <form class="space-y-4" @submit.prevent="handleSubmit">
              <div class="space-y-2">
                <Label for="name-map">Name</Label>
                <Input id="name-map" v-model="name" placeholder="Your name" required />
              </div>
              <div class="space-y-2">
                <Label for="email-map">Email</Label>
                <Input id="email-map" v-model="email" type="email" placeholder="your@email.com" required />
              </div>
              <div class="space-y-2">
                <Label for="message-map">Message</Label>
                <Textarea id="message-map" v-model="message" placeholder="How can we help?" rows="4" required />
              </div>
              <Button type="submit" class="w-full">
                Send Message
                <Send class="ml-2 h-4 w-4" />
              </Button>
            </form>
          </CardContent>
        </Card>
      </div>
    </div>
  </section>
</template>

// src/components/blocks/marketing/contact-section.tsx
import * as React from 'react'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Textarea } from '@/components/ui/textarea'
import { Label } from '@/components/ui/label'
import { Card, CardContent } from '@/components/ui/card'
import { cn } from '@/lib/utils'
import { Mail, Phone, MapPin, Clock, Send, MessageSquare } from 'lucide-react'

export interface ContactInfo {
  email?: string
  phone?: string
  address?: string
  hours?: string
}

// ============================================================================
// CONTACT VARIANT 1: Split with Form
// ============================================================================
export interface ContactSplitProps {
  title?: string
  description?: string
  contactInfo?: ContactInfo
  onSubmit?: (data: { name: string; email: string; subject: string; message: string }) => void
  className?: string
}

export function ContactSplit({
  title = 'Get in touch',
  description = "We'd love to hear from you. Send us a message and we'll respond as soon as possible.",
  contactInfo,
  onSubmit,
  className,
}: ContactSplitProps) {
  const [formData, setFormData] = React.useState({
    name: '',
    email: '',
    subject: '',
    message: '',
  })

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault()
    onSubmit?.(formData)
    setFormData({ name: '', email: '', subject: '', message: '' })
  }

  return (
    <section className={cn('py-16 px-4 md:px-8 lg:px-16', className)}>
      <div className="max-w-6xl mx-auto">
        <div className="grid lg:grid-cols-2 gap-12">
          {/* Info side */}
          <div className="space-y-8">
            <div className="space-y-4">
              <h2 className="text-3xl md:text-4xl font-black uppercase tracking-tight">
                {title}
              </h2>
              <p className="text-lg text-muted-foreground font-medium">
                {description}
              </p>
            </div>

            {contactInfo && (
              <div className="space-y-4">
                {contactInfo.email && (
                  <ContactInfoItem
                    icon={<Mail className="h-5 w-5" />}
                    label="Email"
                    value={contactInfo.email}
                    href={`mailto:${contactInfo.email}`}
                  />
                )}
                {contactInfo.phone && (
                  <ContactInfoItem
                    icon={<Phone className="h-5 w-5" />}
                    label="Phone"
                    value={contactInfo.phone}
                    href={`tel:${contactInfo.phone}`}
                  />
                )}
                {contactInfo.address && (
                  <ContactInfoItem
                    icon={<MapPin className="h-5 w-5" />}
                    label="Address"
                    value={contactInfo.address}
                  />
                )}
                {contactInfo.hours && (
                  <ContactInfoItem
                    icon={<Clock className="h-5 w-5" />}
                    label="Hours"
                    value={contactInfo.hours}
                  />
                )}
              </div>
            )}
          </div>

          {/* Form side */}
          <div className="border-3 border-foreground bg-card p-8 shadow-[6px_6px_0px_hsl(var(--shadow-color))]">
            <form onSubmit={handleSubmit} className="space-y-6">
              <div className="space-y-2">
                <Label htmlFor="name" className="font-bold uppercase text-sm">
                  Name
                </Label>
                <Input
                  id="name"
                  value={formData.name}
                  onChange={(e) => setFormData({ ...formData, name: e.target.value })}
                  placeholder="Your name"
                  required
                />
              </div>

              <div className="space-y-2">
                <Label htmlFor="email" className="font-bold uppercase text-sm">
                  Email
                </Label>
                <Input
                  id="email"
                  type="email"
                  value={formData.email}
                  onChange={(e) => setFormData({ ...formData, email: e.target.value })}
                  placeholder="your@email.com"
                  required
                />
              </div>

              <div className="space-y-2">
                <Label htmlFor="subject" className="font-bold uppercase text-sm">
                  Subject
                </Label>
                <Input
                  id="subject"
                  value={formData.subject}
                  onChange={(e) => setFormData({ ...formData, subject: e.target.value })}
                  placeholder="What's this about?"
                  required
                />
              </div>

              <div className="space-y-2">
                <Label htmlFor="message" className="font-bold uppercase text-sm">
                  Message
                </Label>
                <Textarea
                  id="message"
                  value={formData.message}
                  onChange={(e) => setFormData({ ...formData, message: e.target.value })}
                  placeholder="How can we help?"
                  rows={5}
                  required
                />
              </div>

              <Button type="submit" size="lg" className="w-full">
                Send Message
                <Send className="ml-2 h-4 w-4" />
              </Button>
            </form>
          </div>
        </div>
      </div>
    </section>
  )
}

// ============================================================================
// CONTACT VARIANT 2: Centered Form
// ============================================================================
export interface ContactCenteredProps {
  title?: string
  description?: string
  onSubmit?: (data: { name: string; email: string; subject: string; message: string }) => void
  className?: string
}

export function ContactCentered({
  title = 'Contact Us',
  description = 'Fill out the form below and we\'ll get back to you as soon as possible.',
  onSubmit,
  className,
}: ContactCenteredProps) {
  const [formData, setFormData] = React.useState({
    name: '',
    email: '',
    subject: '',
    message: '',
  })

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault()
    onSubmit?.(formData)
    setFormData({ name: '', email: '', subject: '', message: '' })
  }

  return (
    <section className={cn('py-16 px-4 md:px-8 lg:px-16 bg-muted/30', className)}>
      <div className="max-w-2xl mx-auto">
        <div className="text-center mb-8 space-y-4">
          <MessageSquare className="h-12 w-12 mx-auto text-primary" />
          <h2 className="text-3xl md:text-4xl font-black uppercase tracking-tight">
            {title}
          </h2>
          <p className="text-muted-foreground font-medium">
            {description}
          </p>
        </div>

        <div className="border-3 border-foreground bg-card p-8 shadow-[6px_6px_0px_hsl(var(--shadow-color))]">
          <form onSubmit={handleSubmit} className="space-y-6">
            <div className="grid md:grid-cols-2 gap-4">
              <div className="space-y-2">
                <Label htmlFor="name" className="font-bold uppercase text-sm">
                  Name
                </Label>
                <Input
                  id="name"
                  value={formData.name}
                  onChange={(e) => setFormData({ ...formData, name: e.target.value })}
                  placeholder="Your name"
                  required
                />
              </div>

              <div className="space-y-2">
                <Label htmlFor="email" className="font-bold uppercase text-sm">
                  Email
                </Label>
                <Input
                  id="email"
                  type="email"
                  value={formData.email}
                  onChange={(e) => setFormData({ ...formData, email: e.target.value })}
                  placeholder="your@email.com"
                  required
                />
              </div>
            </div>

            <div className="space-y-2">
              <Label htmlFor="subject" className="font-bold uppercase text-sm">
                Subject
              </Label>
              <Input
                id="subject"
                value={formData.subject}
                onChange={(e) => setFormData({ ...formData, subject: e.target.value })}
                placeholder="What's this about?"
                required
              />
            </div>

            <div className="space-y-2">
              <Label htmlFor="message" className="font-bold uppercase text-sm">
                Message
              </Label>
              <Textarea
                id="message"
                value={formData.message}
                onChange={(e) => setFormData({ ...formData, message: e.target.value })}
                placeholder="Tell us more..."
                rows={6}
                required
              />
            </div>

            <Button type="submit" size="lg" className="w-full">
              Send Message
              <Send className="ml-2 h-4 w-4" />
            </Button>
          </form>
        </div>
      </div>
    </section>
  )
}

// ============================================================================
// CONTACT VARIANT 3: With Cards
// ============================================================================
export interface ContactWithCardsProps {
  title?: string
  description?: string
  contactMethods: Array<{
    icon: React.ReactNode
    title: string
    description: string
    action: { label: string; href: string }
  }>
  className?: string
}

export function ContactWithCards({
  title = 'Get in touch',
  description = 'Choose your preferred way to reach us.',
  contactMethods,
  className,
}: ContactWithCardsProps) {
  const cardColors = [
    'bg-primary/10',
    'bg-secondary/10',
    'bg-accent/10',
  ]

  return (
    <section className={cn('py-16 px-4 md:px-8 lg:px-16', className)}>
      <div className="max-w-5xl mx-auto">
        <div className="text-center mb-12 space-y-4">
          <h2 className="text-3xl md:text-4xl font-black uppercase tracking-tight">
            {title}
          </h2>
          <p className="text-lg text-muted-foreground font-medium">
            {description}
          </p>
        </div>

        <div className="grid md:grid-cols-3 gap-6">
          {contactMethods.map((method, index) => (
            <Card
              key={method.title}
              className={cn(
                'hover:translate-x-[-4px] hover:translate-y-[-4px] hover:shadow-[8px_8px_0px_hsl(var(--shadow-color))] transition-all',
                cardColors[index % 3]
              )}
            >
              <CardContent className="p-6 text-center space-y-4">
                <div className="w-14 h-14 mx-auto flex items-center justify-center border-3 border-foreground bg-card shadow-[3px_3px_0px_hsl(var(--shadow-color))]">
                  {method.icon}
                </div>
                <h3 className="font-black uppercase text-lg">{method.title}</h3>
                <p className="text-sm text-muted-foreground">{method.description}</p>
                <Button variant="outline" asChild>
                  <a href={method.action.href}>{method.action.label}</a>
                </Button>
              </CardContent>
            </Card>
          ))}
        </div>
      </div>
    </section>
  )
}

// ============================================================================
// CONTACT VARIANT 4: With Map Placeholder
// ============================================================================
export interface ContactWithMapProps {
  title?: string
  contactInfo?: ContactInfo
  mapPlaceholder?: React.ReactNode
  onSubmit?: (data: { name: string; email: string; message: string }) => void
  className?: string
}

export function ContactWithMap({
  title = 'Visit Us',
  contactInfo,
  mapPlaceholder,
  onSubmit,
  className,
}: ContactWithMapProps) {
  const [formData, setFormData] = React.useState({
    name: '',
    email: '',
    message: '',
  })

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault()
    onSubmit?.(formData)
    setFormData({ name: '', email: '', message: '' })
  }

  return (
    <section className={cn('py-16 px-4 md:px-8 lg:px-16', className)}>
      <div className="max-w-6xl mx-auto">
        <h2 className="text-3xl md:text-4xl font-black uppercase tracking-tight text-center mb-12">
          {title}
        </h2>

        <div className="grid lg:grid-cols-2 gap-8">
          {/* Map/Image placeholder */}
          <div className="border-3 border-foreground shadow-[6px_6px_0px_hsl(var(--shadow-color))] overflow-hidden h-[400px] lg:h-full lg:min-h-[400px]">
            {mapPlaceholder || (
              <div className="w-full h-full bg-muted flex items-center justify-center">
                <MapPin className="h-16 w-16 text-muted-foreground" />
              </div>
            )}
          </div>

          {/* Contact info and form */}
          <div className="space-y-8">
            {contactInfo && (
              <div className="space-y-4">
                {contactInfo.address && (
                  <ContactInfoItem
                    icon={<MapPin className="h-5 w-5" />}
                    label="Address"
                    value={contactInfo.address}
                  />
                )}
                {contactInfo.phone && (
                  <ContactInfoItem
                    icon={<Phone className="h-5 w-5" />}
                    label="Phone"
                    value={contactInfo.phone}
                    href={`tel:${contactInfo.phone}`}
                  />
                )}
                {contactInfo.email && (
                  <ContactInfoItem
                    icon={<Mail className="h-5 w-5" />}
                    label="Email"
                    value={contactInfo.email}
                    href={`mailto:${contactInfo.email}`}
                  />
                )}
                {contactInfo.hours && (
                  <ContactInfoItem
                    icon={<Clock className="h-5 w-5" />}
                    label="Hours"
                    value={contactInfo.hours}
                  />
                )}
              </div>
            )}

            <form onSubmit={handleSubmit} className="space-y-4">
              <div className="space-y-2">
                <Label htmlFor="map-name" className="font-bold uppercase text-sm">Name</Label>
                <Input
                  id="map-name"
                  value={formData.name}
                  onChange={(e) => setFormData({ ...formData, name: e.target.value })}
                  placeholder="Your name"
                  required
                />
              </div>
              <div className="space-y-2">
                <Label htmlFor="map-email" className="font-bold uppercase text-sm">Email</Label>
                <Input
                  id="map-email"
                  type="email"
                  value={formData.email}
                  onChange={(e) => setFormData({ ...formData, email: e.target.value })}
                  placeholder="Your email"
                  required
                />
              </div>
              <div className="space-y-2">
                <Label htmlFor="map-message" className="font-bold uppercase text-sm">Message</Label>
                <Textarea
                  id="map-message"
                  value={formData.message}
                  onChange={(e) => setFormData({ ...formData, message: e.target.value })}
                  placeholder="Your message"
                  rows={4}
                  required
                />
              </div>
              <Button type="submit" className="w-full">
                Send Message
                <Send className="ml-2 h-4 w-4" />
              </Button>
            </form>
          </div>
        </div>
      </div>
    </section>
  )
}

// ============================================================================
// Helper Components
// ============================================================================
function ContactInfoItem({
  icon,
  label,
  value,
  href,
}: {
  icon: React.ReactNode
  label: string
  value: string
  href?: string
}) {
  const content = (
    <div className="flex items-start gap-4">
      <div className="w-10 h-10 flex items-center justify-center border-2 border-foreground bg-muted shrink-0">
        {icon}
      </div>
      <div>
        <p className="text-xs font-bold uppercase tracking-wide text-muted-foreground">
          {label}
        </p>
        <p className="font-medium">{value}</p>
      </div>
    </div>
  )

  if (href) {
    return (
      <a href={href} className="block hover:opacity-80 transition-opacity">
        {content}
      </a>
    )
  }

  return content
}

// ============================================================================
// Export all variants
// ============================================================================
export const ContactSection = {
  Split: ContactSplit,
  Centered: ContactCentered,
  WithCards: ContactWithCards,
  WithMap: ContactWithMap,
}
