// packages/vue/src/components/blocks/marketing/CTASection.vue
<script setup lang="ts">
import { ref } from 'vue'
import { cn } from '@/lib/utils'
import Button from '@/components/ui/Button.vue'
import Input from '@/components/ui/Input.vue'
import { ArrowRight, Mail, X } from 'lucide-vue-next'

type CTAVariant = 'simple' | 'withBackground' | 'newsletter' | 'split' | 'banner'

interface CTASectionProps {
  variant?: CTAVariant
  title: string
  description?: string
  primaryAction?: { label: string; onClick?: () => void }
  secondaryAction?: { label: string; onClick?: () => void }
  backgroundImage?: string
  class?: string
}

const props = withDefaults(defineProps<CTASectionProps>(), {
  variant: 'simple',
})

const emit = defineEmits<{
  (e: 'subscribe', email: string): void
  (e: 'dismiss'): void
}>()

const email = ref('')
const bannerVisible = ref(true)

const emailError = ref('')

const handleSubscribe = () => {
  emailError.value = ''
  const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/
  if (!email.value || !emailRegex.test(email.value)) {
    emailError.value = 'Please enter a valid email address.'
    return
  }
  emit('subscribe', email.value)
  email.value = ''
}
</script>

<template>
  <!-- Simple Variant -->
  <section
    v-if="variant === 'simple'"
    :class="cn('py-20 px-4 md:px-8 lg:px-16', props.class)"
  >
    <div class="max-w-4xl mx-auto text-center space-y-6">
      <h2 class="text-3xl md:text-4xl font-black uppercase tracking-tight">
        {{ title }}
      </h2>
      <p v-if="description" class="text-lg text-muted-foreground font-medium max-w-2xl mx-auto">
        {{ description }}
      </p>
      <div class="flex flex-col sm:flex-row gap-4 justify-center">
        <Button v-if="primaryAction" size="lg" @click="primaryAction.onClick">
          {{ primaryAction.label }}
          <ArrowRight class="ml-2 h-4 w-4" />
        </Button>
        <Button v-if="secondaryAction" size="lg" variant="outline" @click="secondaryAction.onClick">
          {{ secondaryAction.label }}
        </Button>
      </div>
    </div>
  </section>

  <!-- WithBackground Variant -->
  <section
    v-else-if="variant === 'withBackground'"
    :class="cn('py-20 px-4 md:px-8 lg:px-16 relative overflow-hidden', props.class)"
  >
    <div
      v-if="backgroundImage"
      class="absolute inset-0 bg-cover bg-center"
      :style="{ backgroundImage: `url(${backgroundImage})` }"
    />
    <div class="absolute inset-0 bg-foreground/80" />

    <div class="relative max-w-4xl mx-auto text-center space-y-6">
      <h2 class="text-3xl md:text-4xl font-black uppercase tracking-tight text-background">
        {{ title }}
      </h2>
      <p v-if="description" class="text-lg text-background/80 font-medium max-w-2xl mx-auto">
        {{ description }}
      </p>
      <div class="flex flex-col sm:flex-row gap-4 justify-center">
        <Button v-if="primaryAction" size="lg" variant="secondary" @click="primaryAction.onClick">
          {{ primaryAction.label }}
          <ArrowRight class="ml-2 h-4 w-4" />
        </Button>
        <Button v-if="secondaryAction" size="lg" variant="outline" class="border-background text-background hover:bg-background hover:text-foreground" @click="secondaryAction.onClick">
          {{ secondaryAction.label }}
        </Button>
      </div>
    </div>
  </section>

  <!-- Newsletter Variant -->
  <section
    v-else-if="variant === 'newsletter'"
    :class="cn('py-16 px-4 md:px-8 lg:px-16 bg-primary', props.class)"
  >
    <div class="max-w-4xl mx-auto">
      <div class="border-3 border-foreground bg-background p-8 md:p-12 shadow-[8px_8px_0px_hsl(var(--shadow-color))]">
        <div class="grid md:grid-cols-2 gap-8 items-center">
          <div>
            <h2 class="text-2xl md:text-3xl font-black uppercase tracking-tight mb-3">
              {{ title }}
            </h2>
            <p v-if="description" class="text-muted-foreground font-medium">
              {{ description }}
            </p>
          </div>
          <form class="flex gap-3" @submit.prevent="handleSubscribe">
            <div class="relative flex-1">
              <Mail class="absolute left-3 top-1/2 -translate-y-1/2 h-5 w-5 text-muted-foreground" />
              <Input
                v-model="email"
                type="email"
                placeholder="Enter your email"
                class="pl-10"
                required
              />
            </div>
            <Button type="submit">
              Subscribe
            </Button>
          </form>
          <p v-if="emailError" class="text-sm text-destructive font-medium mt-1">{{ emailError }}</p>
        </div>
      </div>
    </div>
  </section>

  <!-- Split Variant -->
  <section
    v-else-if="variant === 'split'"
    :class="cn('py-16 px-4 md:px-8 lg:px-16', props.class)"
  >
    <div class="max-w-6xl mx-auto">
      <div class="grid md:grid-cols-2 gap-8 items-center border-3 border-foreground shadow-[6px_6px_0px_hsl(var(--shadow-color))]">
        <div class="p-8 md:p-12 bg-primary text-primary-foreground">
          <h2 class="text-2xl md:text-3xl font-black uppercase tracking-tight mb-4">
            {{ title }}
          </h2>
          <p v-if="description" class="font-medium opacity-90">
            {{ description }}
          </p>
        </div>
        <div class="p-8 md:p-12 flex flex-col sm:flex-row gap-4 justify-center">
          <Button v-if="primaryAction" size="lg" @click="primaryAction.onClick">
            {{ primaryAction.label }}
            <ArrowRight class="ml-2 h-4 w-4" />
          </Button>
          <Button v-if="secondaryAction" size="lg" variant="outline" @click="secondaryAction.onClick">
            {{ secondaryAction.label }}
          </Button>
        </div>
      </div>
    </div>
  </section>

  <!-- Banner Variant -->
  <div
    v-else-if="variant === 'banner' && bannerVisible"
    :class="cn('fixed bottom-0 left-0 right-0 z-50 border-t-3 border-foreground bg-accent p-4', props.class)"
  >
    <div class="max-w-7xl mx-auto flex flex-col sm:flex-row items-center justify-between gap-4">
      <div class="flex items-center gap-4">
        <p class="font-bold text-accent-foreground">
          {{ title }}
        </p>
        <p v-if="description" class="text-sm text-accent-foreground/80 hidden md:block">
          {{ description }}
        </p>
      </div>
      <div class="flex items-center gap-3">
        <Button v-if="primaryAction" size="sm" @click="primaryAction.onClick">
          {{ primaryAction.label }}
        </Button>
        <Button
          size="icon"
          variant="ghost"
          class="h-8 w-8"
          @click="bannerVisible = false; emit('dismiss')"
        >
          <X class="h-4 w-4" />
        </Button>
      </div>
    </div>
  </div>
</template>

// src/components/blocks/marketing/cta-section.tsx
import * as React from 'react'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { cn } from '@/lib/utils'
import { ArrowRight, Mail, Sparkles, Zap } from 'lucide-react'

// ============================================================================
// CTA VARIANT 1: Simple Centered
// ============================================================================
export interface CTASimpleProps {
  title: string
  description?: string
  primaryAction: { label: string; href?: string; onClick?: () => void }
  secondaryAction?: { label: string; href?: string; onClick?: () => void }
  className?: string
}

export function CTASimple({
  title,
  description,
  primaryAction,
  secondaryAction,
  className,
}: CTASimpleProps) {
  return (
    <section className={cn('py-16 px-4 md:px-8 lg:px-16', className)}>
      <div className="max-w-4xl mx-auto text-center space-y-6">
        <h2 className="text-3xl md:text-4xl font-black uppercase tracking-tight">
          {title}
        </h2>

        {description && (
          <p className="text-lg text-muted-foreground font-medium max-w-2xl mx-auto">
            {description}
          </p>
        )}

        <div className="flex flex-col sm:flex-row gap-4 justify-center">
          {primaryAction.href ? (
            <Button size="lg" asChild>
              <a href={primaryAction.href}>{primaryAction.label}<ArrowRight className="ml-2 h-4 w-4" /></a>
            </Button>
          ) : (
            <Button size="lg" onClick={primaryAction.onClick}>
              {primaryAction.label}
              <ArrowRight className="ml-2 h-4 w-4" />
            </Button>
          )}
          {secondaryAction && (
            secondaryAction.href ? (
              <Button size="lg" variant="outline" asChild>
                <a href={secondaryAction.href}>{secondaryAction.label}</a>
              </Button>
            ) : (
              <Button size="lg" variant="outline" onClick={secondaryAction.onClick}>
                {secondaryAction.label}
              </Button>
            )
          )}
        </div>
      </div>
    </section>
  )
}

// ============================================================================
// CTA VARIANT 2: With Background
// ============================================================================
export interface CTAWithBackgroundProps {
  title: string
  description?: string
  primaryAction: { label: string; href?: string; onClick?: () => void }
  backgroundColor?: 'primary' | 'secondary' | 'accent' | 'muted'
  className?: string
}

export function CTAWithBackground({
  title,
  description,
  primaryAction,
  backgroundColor = 'primary',
  className,
}: CTAWithBackgroundProps) {
  const bgColors = {
    primary: 'bg-primary text-primary-foreground',
    secondary: 'bg-secondary text-secondary-foreground',
    accent: 'bg-accent text-accent-foreground',
    muted: 'bg-muted text-foreground',
  }

  return (
    <section className={cn('py-16 px-4 md:px-8 lg:px-16', className)}>
      <div
        className={cn(
          'max-w-5xl mx-auto border-3 border-foreground p-8 md:p-12 shadow-[8px_8px_0px_hsl(var(--shadow-color))]',
          bgColors[backgroundColor]
        )}
      >
        <div className="text-center space-y-6">
          <Sparkles className="h-12 w-12 mx-auto" />

          <h2 className="text-3xl md:text-4xl font-black uppercase tracking-tight">
            {title}
          </h2>

          {description && (
            <p className="text-lg font-medium max-w-2xl mx-auto opacity-90">
              {description}
            </p>
          )}

          {primaryAction.href ? (
            <Button
              size="lg"
              variant={backgroundColor === 'muted' ? 'default' : 'outline'}
              className={backgroundColor !== 'muted' ? 'bg-background text-foreground hover:bg-background/90' : ''}
              asChild
            >
              <a href={primaryAction.href}>{primaryAction.label}<Zap className="ml-2 h-4 w-4" /></a>
            </Button>
          ) : (
            <Button
              size="lg"
              variant={backgroundColor === 'muted' ? 'default' : 'outline'}
              className={backgroundColor !== 'muted' ? 'bg-background text-foreground hover:bg-background/90' : ''}
              onClick={primaryAction.onClick}
            >
              {primaryAction.label}
              <Zap className="ml-2 h-4 w-4" />
            </Button>
          )}
        </div>
      </div>
    </section>
  )
}

// ============================================================================
// CTA VARIANT 3: Newsletter
// ============================================================================
export interface CTANewsletterProps {
  title: string
  description?: string
  placeholder?: string
  buttonLabel?: string
  onSubmit?: (email: string) => void
  className?: string
}

export function CTANewsletter({
  title,
  description,
  placeholder = 'Enter your email',
  buttonLabel = 'Subscribe',
  onSubmit,
  className,
}: CTANewsletterProps) {
  const [email, setEmail] = React.useState('')

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault()
    onSubmit?.(email)
    setEmail('')
  }

  return (
    <section className={cn('py-16 px-4 md:px-8 lg:px-16 bg-muted/30', className)}>
      <div className="max-w-2xl mx-auto text-center space-y-6">
        <Mail className="h-12 w-12 mx-auto text-primary" />

        <h2 className="text-2xl md:text-3xl font-black uppercase tracking-tight">
          {title}
        </h2>

        {description && (
          <p className="text-muted-foreground font-medium">
            {description}
          </p>
        )}

        <form onSubmit={handleSubmit} className="flex flex-col sm:flex-row gap-3 max-w-md mx-auto">
          <Input
            type="email"
            placeholder={placeholder}
            value={email}
            onChange={(e) => setEmail(e.target.value)}
            className="flex-1"
            required
          />
          <Button type="submit" size="lg">
            {buttonLabel}
            <ArrowRight className="ml-2 h-4 w-4" />
          </Button>
        </form>

        <p className="text-xs text-muted-foreground">
          No spam. Unsubscribe anytime.
        </p>
      </div>
    </section>
  )
}

// ============================================================================
// CTA VARIANT 4: Split with Image
// ============================================================================
export interface CTASplitProps {
  title: string
  description?: string
  primaryAction: { label: string; href?: string; onClick?: () => void }
  secondaryAction?: { label: string; href?: string; onClick?: () => void }
  imageSrc: string
  imageAlt?: string
  imagePosition?: 'left' | 'right'
  className?: string
}

export function CTASplit({
  title,
  description,
  primaryAction,
  secondaryAction,
  imageSrc,
  imageAlt = 'CTA image',
  imagePosition = 'right',
  className,
}: CTASplitProps) {
  return (
    <section className={cn('py-16 px-4 md:px-8 lg:px-16', className)}>
      <div className="max-w-6xl mx-auto border-3 border-foreground shadow-[8px_8px_0px_hsl(var(--shadow-color))] overflow-hidden">
        <div
          className={cn(
            'grid md:grid-cols-2',
            imagePosition === 'left' && 'md:[&>*:first-child]:order-2'
          )}
        >
          <div className="p-8 md:p-12 flex flex-col justify-center space-y-6">
            <h2 className="text-2xl md:text-3xl font-black uppercase tracking-tight">
              {title}
            </h2>

            {description && (
              <p className="text-muted-foreground font-medium">
                {description}
              </p>
            )}

            <div className="flex flex-col sm:flex-row gap-3">
              {primaryAction.href ? (
                <Button size="lg" asChild>
                  <a href={primaryAction.href}>{primaryAction.label}<ArrowRight className="ml-2 h-4 w-4" /></a>
                </Button>
              ) : (
                <Button size="lg" onClick={primaryAction.onClick}>
                  {primaryAction.label}
                  <ArrowRight className="ml-2 h-4 w-4" />
                </Button>
              )}
              {secondaryAction && (
                secondaryAction.href ? (
                  <Button size="lg" variant="outline" asChild>
                    <a href={secondaryAction.href}>{secondaryAction.label}</a>
                  </Button>
                ) : (
                  <Button size="lg" variant="outline" onClick={secondaryAction.onClick}>
                    {secondaryAction.label}
                  </Button>
                )
              )}
            </div>
          </div>

          <div className="bg-muted">
            <img
              src={imageSrc}
              alt={imageAlt}
              className="w-full h-full object-cover"
            />
          </div>
        </div>
      </div>
    </section>
  )
}

// ============================================================================
// CTA VARIANT 5: Banner
// ============================================================================
export interface CTABannerProps {
  text: string
  action: { label: string; href?: string; onClick?: () => void }
  dismissible?: boolean
  onDismiss?: () => void
  variant?: 'primary' | 'secondary' | 'accent' | 'warning'
  className?: string
}

export function CTABanner({
  text,
  action,
  dismissible = false,
  onDismiss,
  variant = 'primary',
  className,
}: CTABannerProps) {
  const [isVisible, setIsVisible] = React.useState(true)

  const variantStyles = {
    primary: 'bg-primary text-primary-foreground',
    secondary: 'bg-secondary text-secondary-foreground',
    accent: 'bg-accent text-accent-foreground',
    warning: 'bg-yellow-500 text-foreground',
  }

  if (!isVisible) return null

  return (
    <div
      className={cn(
        'relative py-3 px-4 border-b-3 border-foreground',
        variantStyles[variant],
        className
      )}
    >
      <div className="max-w-7xl mx-auto flex flex-col sm:flex-row items-center justify-center gap-3 text-center sm:text-left">
        <p className="font-bold text-sm">
          {text}
        </p>
        {action.href ? (
          <Button size="sm" variant="outline" className="bg-background text-foreground hover:bg-background/90 shrink-0" asChild>
            <a href={action.href}>{action.label}<ArrowRight className="ml-1 h-3 w-3" /></a>
          </Button>
        ) : (
          <Button
            size="sm"
            variant="outline"
            className="bg-background text-foreground hover:bg-background/90 shrink-0"
            onClick={action.onClick}
          >
            {action.label}
            <ArrowRight className="ml-1 h-3 w-3" />
          </Button>
        )}
        {dismissible && (
          <button
            aria-label="Dismiss"
            onClick={() => {
              setIsVisible(false)
              onDismiss?.()
            }}
            className="absolute right-4 text-current opacity-70 hover:opacity-100"
          >
            ×
          </button>
        )}
      </div>
    </div>
  )
}

// ============================================================================
// Export all variants
// ============================================================================
export const CTASection = {
  Simple: CTASimple,
  WithBackground: CTAWithBackground,
  Newsletter: CTANewsletter,
  Split: CTASplit,
  Banner: CTABanner,
}
