// packages/vue/src/components/ui/Marquee.vue
<script setup lang="ts">
import { computed } from 'vue'
import { cn } from '@/lib/utils'

interface Props {
  class?: string
  direction?: 'left' | 'right'
  speed?: 'slow' | 'normal' | 'fast'
  pauseOnHover?: boolean
  bordered?: boolean
  repeat?: number
}

const props = withDefaults(defineProps<Props>(), {
  direction: 'left',
  speed: 'normal',
  pauseOnHover: true,
  bordered: true,
  repeat: 4,
})

const speedClasses = {
  slow: 'animate-marquee-slow',
  normal: 'animate-marquee',
  fast: 'animate-marquee-fast',
}

const animationClass = computed(() =>
  props.direction === 'right' ? 'animate-marquee-reverse' : speedClasses[props.speed]
)

const animationDirection = computed(() =>
  props.direction === 'right' ? 'reverse' : 'normal'
)

</script>

<template>
  <div
    :class="
      cn(
        'flex overflow-hidden',
        bordered && 'border-3 border-foreground bg-background',
        props.class
      )
    "
  >
    <div
      :class="
        cn(
          'marquee-content flex shrink-0 items-center gap-8 py-3',
          animationClass,
          pauseOnHover && 'hover:[animation-play-state:paused]'
        )
      "
      :style="{ animationDirection }"
    >
      <slot v-for="_n in repeat" :key="_n" />
    </div>
    <div
      :class="
        cn(
          'marquee-content flex shrink-0 items-center gap-8 py-3',
          animationClass,
          pauseOnHover && 'hover:[animation-play-state:paused]'
        )
      "
      :style="{ animationDirection }"
      aria-hidden="true"
    >
      <slot v-for="_m in repeat" :key="`dup-${_m}`" />
    </div>
  </div>
</template>

// registry/default/ui/marquee.tsx
import * as React from 'react'
import { cn } from '@/lib/utils'

interface MarqueeProps extends React.HTMLAttributes<HTMLDivElement> {
  /** Content to display in the marquee */
  children: React.ReactNode
  /** Direction of the marquee animation */
  direction?: 'left' | 'right'
  /** Speed of the animation: 'slow' | 'normal' | 'fast' */
  speed?: 'slow' | 'normal' | 'fast'
  /** Pause animation on hover */
  pauseOnHover?: boolean
  /** Show neubrutalism border styling */
  bordered?: boolean
  /** Number of times to repeat the content (for seamless loop) */
  repeat?: number
}

const speedClasses = {
  slow: 'animate-marquee-slow',
  normal: 'animate-marquee',
  fast: 'animate-marquee-fast',
}

const reverseSpeedClasses = {
  slow: 'animate-marquee-slow-reverse',
  normal: 'animate-marquee-reverse',
  fast: 'animate-marquee-fast-reverse',
}

const Marquee = React.forwardRef<HTMLDivElement, MarqueeProps>(
  (
    {
      className,
      children,
      direction = 'left',
      speed = 'normal',
      pauseOnHover = true,
      bordered = true,
      repeat = 4,
      ...props
    },
    ref
  ) => {
    const animationClass = direction === 'right' ? reverseSpeedClasses[speed] : speedClasses[speed]

    return (
      <div
        ref={ref}
        className={cn(
          'flex overflow-hidden',
          bordered && 'border-3 border-foreground bg-background',
          className
        )}
        {...props}
      >
        <div
          className={cn(
            'marquee-content flex shrink-0 items-center gap-8 py-3',
            animationClass,
            pauseOnHover && 'hover:[animation-play-state:paused]'
          )}
        >
          {Array.from({ length: repeat }).map((_, i) => (
            <React.Fragment key={i}>{children}</React.Fragment>
          ))}
        </div>
        <div
          className={cn(
            'marquee-content flex shrink-0 items-center gap-8 py-3',
            animationClass,
            pauseOnHover && 'hover:[animation-play-state:paused]'
          )}
          aria-hidden="true"
        >
          {Array.from({ length: repeat }).map((_, i) => (
            <React.Fragment key={i}>{children}</React.Fragment>
          ))}
        </div>
      </div>
    )
  }
)
Marquee.displayName = 'Marquee'

interface MarqueeItemProps extends React.HTMLAttributes<HTMLSpanElement> {
  children: React.ReactNode
}

const MarqueeItem = React.forwardRef<HTMLSpanElement, MarqueeItemProps>(
  ({ className, children, ...props }, ref) => {
    return (
      <span
        ref={ref}
        className={cn(
          'inline-flex items-center gap-2 whitespace-nowrap px-4 text-lg font-bold uppercase tracking-wide',
          className
        )}
        {...props}
      >
        {children}
      </span>
    )
  }
)
MarqueeItem.displayName = 'MarqueeItem'

interface MarqueeSeparatorProps extends React.HTMLAttributes<HTMLSpanElement> {
  /** Separator character or element */
  children?: React.ReactNode
}

const MarqueeSeparator = React.forwardRef<HTMLSpanElement, MarqueeSeparatorProps>(
  ({ className, children = '/', ...props }, ref) => {
    return (
      <span
        ref={ref}
        className={cn('text-2xl font-black text-muted-foreground', className)}
        {...props}
      >
        {children}
      </span>
    )
  }
)
MarqueeSeparator.displayName = 'MarqueeSeparator'

export { Marquee, MarqueeItem, MarqueeSeparator }
