// packages/vue/src/components/ui/Progress.vue
<script setup lang="ts">
import { computed } from 'vue'
import { ProgressRoot, ProgressIndicator, type ProgressRootProps } from 'reka-ui'
import { cn } from '@/lib/utils'

type ProgressVariant = 'smooth' | 'stepped' | 'marquee'

interface Props extends ProgressRootProps {
  class?: string
  /**
   * smooth  — continuous fill (the pre-v3.5 default)
   * stepped — fill snaps forward in ten discrete notches
   * marquee — indeterminate; a block travelling the track, ignores modelValue
   */
  variant?: ProgressVariant
}

const props = withDefaults(defineProps<Props>(), { variant: 'smooth' })

const indeterminate = computed(() => props.variant === 'marquee')

const clampedValue = computed(() => Math.max(0, Math.min(100, props.modelValue ?? 0)))

// Reka reads null as indeterminate and drops aria-valuenow. Clamp so an
// out-of-range modelValue can't trip its range warning, and keep an omitted
// value indeterminate.
const rootValue = computed(() =>
  indeterminate.value || props.modelValue == null ? null : clampedValue.value
)

// Only the primitive's own props reach ProgressRoot — `class` and `variant`
// are ours and would otherwise land on the DOM node as stray attributes.
const rootProps = computed<ProgressRootProps>(() => ({
  max: props.max,
  getValueLabel: props.getValueLabel,
  asChild: props.asChild,
  as: props.as,
  modelValue: rootValue.value,
}))
</script>

<template>
  <ProgressRoot
    v-bind="rootProps"
    :class="
      cn(
        'relative h-5 w-full overflow-hidden border-3 border-foreground bg-muted shadow-[4px_4px_0px_hsl(var(--shadow-color))]',
        props.class
      )
    "
  >
    <ProgressIndicator
      :class="
        cn(
          'h-full w-full flex-1 bg-primary transition duration-500 ease-out',
          props.variant === 'stepped' && 'bk-progress-stepped',
          indeterminate && 'bk-progress-marquee'
        )
      "
      :style="indeterminate ? undefined : { transform: `translateX(-${100 - clampedValue}%)` }"
    />
  </ProgressRoot>
</template>

// registry/default/ui/progress.tsx
import * as React from 'react'
import * as ProgressPrimitive from '@radix-ui/react-progress'
import { cn } from '@/lib/utils'

type ProgressVariant =
  /** Continuous fill. The pre-v3.5 default. */
  | 'smooth'
  /** Fill snaps forward in ten discrete notches. */
  | 'stepped'
  /** Indeterminate — a block travelling the track. Ignores `value`. */
  | 'marquee'

export interface ProgressProps
  extends React.ComponentPropsWithoutRef<typeof ProgressPrimitive.Root> {
  variant?: ProgressVariant
}

const Progress = React.forwardRef<
  React.ElementRef<typeof ProgressPrimitive.Root>,
  ProgressProps
>(({ className, value, variant = 'smooth', ...props }, ref) => {
  const indeterminate = variant === 'marquee'
  const clampedValue = Math.max(0, Math.min(100, value ?? 0))
  // Radix reads null as indeterminate and drops aria-valuenow. Pass the clamped
  // value so an out-of-range `value` can't trip Radix's range warning, and keep
  // an omitted value indeterminate the way it was before v3.5.
  const ariaValue = indeterminate || value == null ? null : clampedValue
  return (
    <ProgressPrimitive.Root
      ref={ref}
      value={ariaValue}
      className={cn(
        'relative h-5 w-full overflow-hidden border-3 border-foreground bg-muted shadow-[4px_4px_0px_hsl(var(--shadow-color))]',
        className
      )}
      {...props}
    >
      <ProgressPrimitive.Indicator
        className={cn(
          'h-full w-full flex-1 bg-primary transition duration-500 ease-out',
          variant === 'stepped' && 'bk-progress-stepped',
          indeterminate && 'bk-progress-marquee'
        )}
        style={
          indeterminate ? undefined : { transform: `translateX(-${100 - clampedValue}%)` }
        }
      />
    </ProgressPrimitive.Root>
  )
})
Progress.displayName = ProgressPrimitive.Root.displayName

export { Progress }
export type { ProgressVariant }
