// packages/vue/src/components/ui/TreeView.vue
<script lang="ts">
import { type Component, defineComponent, computed, h, type PropType } from 'vue'
import { ChevronRight, Folder, File } from 'lucide-vue-next'
import Collapsible from './Collapsible.vue'
import CollapsibleContent from './CollapsibleContent.vue'
import CollapsibleTrigger from './CollapsibleTrigger.vue'
import Checkbox from './Checkbox.vue'
import { cn } from '@/lib/utils'

export interface TreeNode {
  id: string
  label: string
  icon?: Component
  children?: TreeNode[]
  disabled?: boolean
}

// Recursive TreeViewNode component defined using defineComponent for self-referencing
const TreeViewNode = defineComponent({
  name: 'TreeViewNode',
  props: {
    node: {
      type: Object as PropType<TreeNode>,
      required: true,
    },
    depth: {
      type: Number,
      required: true,
    },
    isExpanded: {
      type: Function as PropType<(id: string) => boolean>,
      required: true,
    },
    isSelected: {
      type: Function as PropType<(id: string) => boolean>,
      required: true,
    },
    toggleExpanded: {
      type: Function as PropType<(id: string) => void>,
      required: true,
    },
    toggleSelected: {
      type: Function as PropType<(id: string, node: TreeNode) => void>,
      required: true,
    },
    handleKeyDown: {
      type: Function as PropType<(event: KeyboardEvent, node: TreeNode) => void>,
      required: true,
    },
    selectionMode: {
      type: String as PropType<'none' | 'single' | 'multiple'>,
      required: true,
    },
    showCheckboxes: {
      type: Boolean,
      required: true,
    },
    showIcons: {
      type: Boolean,
      required: true,
    },
  },
  setup(props) {
    const hasChildren = computed(
      () => props.node.children && props.node.children.length > 0
    )
    const expanded = computed(() => props.isExpanded(props.node.id))
    const selected = computed(() => props.isSelected(props.node.id))

    const IconComponent = computed(() => {
      if (props.node.icon) return props.node.icon
      return hasChildren.value ? Folder : File
    })

    const handleNodeClick = () => {
      if (props.node.disabled) return
      if (props.selectionMode !== 'none') {
        props.toggleSelected(props.node.id, props.node)
      }
    }

    const handleChevronClick = (e: MouseEvent) => {
      e.stopPropagation()
      props.toggleExpanded(props.node.id)
    }

    const handleCheckboxClick = (e: MouseEvent) => {
      e.stopPropagation()
    }

    const handleCheckboxChange = () => {
      if (!props.node.disabled) {
        props.toggleSelected(props.node.id, props.node)
      }
    }

    return () => {
      const nodeContent = h(
        'div',
        {
          class: cn(
            'flex items-center gap-2 px-2 py-1.5 cursor-pointer select-none transition-colors duration-150',
            'hover:bg-muted focus:outline-none focus:bg-muted',
            selected.value && 'bg-accent',
            props.node.disabled && 'opacity-50 cursor-not-allowed'
          ),
          style: { paddingLeft: `${props.depth * 16 + 8}px` },
          tabindex: props.node.disabled ? -1 : 0,
          role: 'treeitem',
          'aria-expanded': hasChildren.value ? expanded.value : undefined,
          'aria-selected': selected.value,
          'aria-disabled': props.node.disabled,
          onKeydown: (e: KeyboardEvent) => props.handleKeyDown(e, props.node),
          onClick: handleNodeClick,
        },
        [
          // Expand/collapse chevron
          hasChildren.value
            ? h(
                'button',
                {
                  type: 'button',
                  class: cn(
                    'flex items-center justify-center w-5 h-5 transition-transform duration-200 flex-shrink-0',
                    expanded.value && 'rotate-90'
                  ),
                  onClick: handleChevronClick,
                  'aria-label': expanded.value ? 'Collapse' : 'Expand',
                },
                h(ChevronRight, { class: 'w-4 h-4 stroke-[3]' })
              )
            : h('span', { class: 'w-5 h-5 flex-shrink-0' }),

          // Checkbox
          props.showCheckboxes && props.selectionMode !== 'none'
            ? h(Checkbox, {
                checked: selected.value,
                disabled: props.node.disabled,
                class:
                  'h-5 w-5 border-2 border-foreground data-[state=checked]:bg-primary data-[state=checked]:shadow-[2px_2px_0px_hsl(var(--shadow-color))]',
                'onUpdate:checked': handleCheckboxChange,
                onClick: handleCheckboxClick,
              })
            : null,

          // Icon
          props.showIcons
            ? h(IconComponent.value, {
                class: 'w-5 h-5 flex-shrink-0 stroke-[2.5]',
              })
            : null,

          // Label
          h(
            'span',
            { class: 'font-medium text-sm truncate' },
            props.node.label
          ),
        ]
      )

      if (hasChildren.value) {
        return h(
          Collapsible,
          {
            open: expanded.value,
            'onUpdate:open': () => props.toggleExpanded(props.node.id),
          },
          () => [
            h(CollapsibleTrigger, { asChild: true }, () => nodeContent),
            h(CollapsibleContent, null, () =>
              h(
                'div',
                { role: 'group' },
                props.node.children!.map((child) =>
                  h(TreeViewNode, {
                    key: child.id,
                    node: child,
                    depth: props.depth + 1,
                    isExpanded: props.isExpanded,
                    isSelected: props.isSelected,
                    toggleExpanded: props.toggleExpanded,
                    toggleSelected: props.toggleSelected,
                    handleKeyDown: props.handleKeyDown,
                    selectionMode: props.selectionMode,
                    showCheckboxes: props.showCheckboxes,
                    showIcons: props.showIcons,
                  })
                )
              )
            ),
          ]
        )
      }

      return nodeContent
    }
  },
})

export { TreeViewNode }
</script>

<script setup lang="ts">
import { ref, computed, watch } from 'vue'

interface TreeViewProps {
  data: TreeNode[]
  expandedIds?: string[]
  selectedIds?: string[]
  selectionMode?: 'none' | 'single' | 'multiple'
  showCheckboxes?: boolean
  showIcons?: boolean
  defaultExpandedIds?: string[]
  defaultSelectedIds?: string[]
  class?: string
}

const props = withDefaults(defineProps<TreeViewProps>(), {
  expandedIds: undefined,
  selectedIds: undefined,
  selectionMode: 'none',
  showCheckboxes: false,
  showIcons: true,
  defaultExpandedIds: () => [],
  defaultSelectedIds: () => [],
})

const emit = defineEmits<{
  'update:expandedIds': [ids: string[]]
  'update:selectedIds': [ids: string[]]
}>()

// Internal state for uncontrolled mode
const internalExpandedIds = ref<string[]>([...props.defaultExpandedIds])
const internalSelectedIds = ref<string[]>([...props.defaultSelectedIds])

// Computed values for controlled/uncontrolled mode
const isExpandedControlled = computed(() => props.expandedIds !== undefined)
const isSelectedControlled = computed(() => props.selectedIds !== undefined)

const currentExpandedIds = computed(() =>
  isExpandedControlled.value ? props.expandedIds! : internalExpandedIds.value
)
const currentSelectedIds = computed(() =>
  isSelectedControlled.value ? props.selectedIds! : internalSelectedIds.value
)

// Sync internal state with controlled props when they change
watch(
  () => props.expandedIds,
  (newVal) => {
    if (newVal !== undefined) {
      internalExpandedIds.value = [...newVal]
    }
  }
)

watch(
  () => props.selectedIds,
  (newVal) => {
    if (newVal !== undefined) {
      internalSelectedIds.value = [...newVal]
    }
  }
)

const isExpanded = (id: string) => currentExpandedIds.value.includes(id)
const isSelected = (id: string) => currentSelectedIds.value.includes(id)

const toggleExpanded = (id: string) => {
  const newExpandedIds = isExpanded(id)
    ? currentExpandedIds.value.filter((i) => i !== id)
    : [...currentExpandedIds.value, id]

  if (!isExpandedControlled.value) {
    internalExpandedIds.value = newExpandedIds
  }
  emit('update:expandedIds', newExpandedIds)
}

const toggleSelected = (id: string, node: TreeNode) => {
  if (node.disabled || props.selectionMode === 'none') return

  let newSelectedIds: string[]

  if (props.selectionMode === 'single') {
    newSelectedIds = isSelected(id) ? [] : [id]
  } else {
    newSelectedIds = isSelected(id)
      ? currentSelectedIds.value.filter((i) => i !== id)
      : [...currentSelectedIds.value, id]
  }

  if (!isSelectedControlled.value) {
    internalSelectedIds.value = newSelectedIds
  }
  emit('update:selectedIds', newSelectedIds)
}

const handleKeyDown = (event: KeyboardEvent, node: TreeNode) => {
  const hasChildren = node.children && node.children.length > 0

  switch (event.key) {
    case 'Enter':
    case ' ':
      event.preventDefault()
      if (props.selectionMode !== 'none') {
        toggleSelected(node.id, node)
      } else if (hasChildren) {
        toggleExpanded(node.id)
      }
      break
    case 'ArrowRight':
      event.preventDefault()
      if (hasChildren && !isExpanded(node.id)) {
        toggleExpanded(node.id)
      }
      break
    case 'ArrowLeft':
      event.preventDefault()
      if (hasChildren && isExpanded(node.id)) {
        toggleExpanded(node.id)
      }
      break
  }
}
</script>

<template>
  <div
    :class="cn('border-3 border-foreground bg-background p-2', props.class)"
    role="tree"
  >
    <TreeViewNode
      v-for="node in data"
      :key="node.id"
      :node="node"
      :depth="0"
      :is-expanded="isExpanded"
      :is-selected="isSelected"
      :toggle-expanded="toggleExpanded"
      :toggle-selected="toggleSelected"
      :handle-key-down="handleKeyDown"
      :selection-mode="selectionMode"
      :show-checkboxes="showCheckboxes"
      :show-icons="showIcons"
    />
  </div>
</template>

// registry/default/ui/tree-view.tsx
import * as React from 'react'
import { ChevronRight, Folder, File } from 'lucide-react'
import { cn } from '@/lib/utils'
import { Checkbox } from '@/components/ui/checkbox'
import {
  Collapsible,
  CollapsibleContent,
  CollapsibleTrigger,
} from '@/components/ui/collapsible'

export interface TreeNode {
  id: string
  label: string
  icon?: React.ReactNode
  children?: TreeNode[]
  disabled?: boolean
}

export interface TreeViewProps extends React.HTMLAttributes<HTMLDivElement> {
  data: TreeNode[]
  expandedIds?: string[]
  onExpandedChange?: (ids: string[]) => void
  selectedIds?: string[]
  onSelectedChange?: (ids: string[]) => void
  selectionMode?: 'none' | 'single' | 'multiple'
  showCheckboxes?: boolean
  showIcons?: boolean
  defaultExpandedIds?: string[]
  defaultSelectedIds?: string[]
}

// Context
interface TreeViewContextValue {
  expandedIds: Set<string>
  toggleExpanded: (id: string) => void
  selectedIds: Set<string>
  toggleSelected: (id: string) => void
  selectionMode: 'none' | 'single' | 'multiple'
  showCheckboxes: boolean
  showIcons: boolean
}

const TreeViewContext = React.createContext<TreeViewContextValue | null>(null)

function useTreeView() {
  const context = React.useContext(TreeViewContext)
  if (!context) {
    throw new Error('TreeView components must be used within a <TreeView />')
  }
  return context
}

const TreeView = React.forwardRef<HTMLDivElement, TreeViewProps>(
  (
    {
      data,
      expandedIds: controlledExpandedIds,
      onExpandedChange,
      selectedIds: controlledSelectedIds,
      onSelectedChange,
      selectionMode = 'none',
      showCheckboxes = false,
      showIcons = true,
      defaultExpandedIds = [],
      defaultSelectedIds = [],
      className,
      ...props
    },
    ref
  ) => {
    const [uncontrolledExpandedIds, setUncontrolledExpandedIds] = React.useState<Set<string>>(
      new Set(defaultExpandedIds)
    )
    const [uncontrolledSelectedIds, setUncontrolledSelectedIds] = React.useState<Set<string>>(
      new Set(defaultSelectedIds)
    )

    const isExpandedControlled = controlledExpandedIds !== undefined
    const isSelectedControlled = controlledSelectedIds !== undefined

    const expandedIds = isExpandedControlled
      ? new Set(controlledExpandedIds)
      : uncontrolledExpandedIds

    const selectedIds = isSelectedControlled
      ? new Set(controlledSelectedIds)
      : uncontrolledSelectedIds

    const toggleExpanded = React.useCallback(
      (id: string) => {
        const newExpandedIds = new Set(expandedIds)
        if (newExpandedIds.has(id)) {
          newExpandedIds.delete(id)
        } else {
          newExpandedIds.add(id)
        }

        if (!isExpandedControlled) {
          setUncontrolledExpandedIds(newExpandedIds)
        }
        onExpandedChange?.(Array.from(newExpandedIds))
      },
      [expandedIds, isExpandedControlled, onExpandedChange]
    )

    const toggleSelected = React.useCallback(
      (id: string) => {
        if (selectionMode === 'none') return

        let newSelectedIds: Set<string>

        if (selectionMode === 'single') {
          newSelectedIds = selectedIds.has(id) ? new Set() : new Set([id])
        } else {
          newSelectedIds = new Set(selectedIds)
          if (newSelectedIds.has(id)) {
            newSelectedIds.delete(id)
          } else {
            newSelectedIds.add(id)
          }
        }

        if (!isSelectedControlled) {
          setUncontrolledSelectedIds(newSelectedIds)
        }
        onSelectedChange?.(Array.from(newSelectedIds))
      },
      [selectedIds, selectionMode, isSelectedControlled, onSelectedChange]
    )

    return (
      <TreeViewContext.Provider
        value={{
          expandedIds,
          toggleExpanded,
          selectedIds,
          toggleSelected,
          selectionMode,
          showCheckboxes,
          showIcons,
        }}
      >
        <div
          ref={ref}
          role="tree"
          className={cn(
            'border-3 border-foreground bg-background p-2',
            'shadow-[4px_4px_0px_hsl(var(--shadow-color))]',
            className
          )}
          {...props}
        >
          {data.map((node) => (
            <TreeNodeItem key={node.id} node={node} level={0} />
          ))}
        </div>
      </TreeViewContext.Provider>
    )
  }
)
TreeView.displayName = 'TreeView'

// Tree Node Component
interface TreeNodeProps {
  node: TreeNode
  level: number
}

function TreeNodeItem({ node, level }: TreeNodeProps) {
  const {
    expandedIds,
    toggleExpanded,
    selectedIds,
    toggleSelected,
    selectionMode,
    showCheckboxes,
    showIcons,
  } = useTreeView()

  const hasChildren = node.children && node.children.length > 0
  const isExpanded = expandedIds.has(node.id)
  const isSelected = selectedIds.has(node.id)

  const handleKeyDown = (e: React.KeyboardEvent) => {
    switch (e.key) {
      case 'Enter':
      case ' ':
        e.preventDefault()
        if (selectionMode !== 'none') {
          toggleSelected(node.id)
        } else if (hasChildren) {
          toggleExpanded(node.id)
        }
        break
      case 'ArrowRight':
        if (hasChildren && !isExpanded) {
          e.preventDefault()
          toggleExpanded(node.id)
        }
        break
      case 'ArrowLeft':
        if (hasChildren && isExpanded) {
          e.preventDefault()
          toggleExpanded(node.id)
        }
        break
      case 'ArrowDown': {
        e.preventDefault()
        const allItems = Array.from(
          document.querySelectorAll<HTMLElement>('[role="treeitem"]')
        )
        const currentIndex = allItems.findIndex((el) => el === e.currentTarget)
        if (currentIndex < allItems.length - 1) {
          allItems[currentIndex + 1].focus()
        }
        break
      }
      case 'ArrowUp': {
        e.preventDefault()
        const allItems = Array.from(
          document.querySelectorAll<HTMLElement>('[role="treeitem"]')
        )
        const currentIndex = allItems.findIndex((el) => el === e.currentTarget)
        if (currentIndex > 0) {
          allItems[currentIndex - 1].focus()
        }
        break
      }
    }
  }

  const content = (
    <div
      role="treeitem"
      aria-selected={isSelected}
      aria-expanded={hasChildren ? isExpanded : undefined}
      aria-disabled={node.disabled}
      tabIndex={node.disabled ? -1 : 0}
      onKeyDown={handleKeyDown}
      onClick={() => {
        if (node.disabled) return
        if (selectionMode !== 'none') {
          toggleSelected(node.id)
        }
      }}
      className={cn(
        'flex items-center gap-2 px-2 py-1.5 cursor-pointer transition-colors',
        'hover:bg-muted focus:outline-none focus:bg-muted',
        isSelected && 'bg-accent',
        node.disabled && 'opacity-50 cursor-not-allowed'
      )}
      style={{ paddingLeft: `${level * 16 + 8}px` }}
    >
      {/* Expand/collapse button */}
      {hasChildren ? (
        <button
          type="button"
          onClick={(e) => {
            e.stopPropagation()
            toggleExpanded(node.id)
          }}
          className="p-0.5 hover:bg-muted-foreground/20 transition-colors"
          aria-label={isExpanded ? `Collapse ${node.label}` : `Expand ${node.label}`}
        >
          <ChevronRight
            className={cn(
              'h-4 w-4 stroke-[3] transition-transform duration-200',
              isExpanded && 'rotate-90'
            )}
          />
        </button>
      ) : (
        <span className="w-5" />
      )}

      {/* Checkbox */}
      {showCheckboxes && selectionMode !== 'none' && (
        <Checkbox
          checked={isSelected}
          onCheckedChange={() => toggleSelected(node.id)}
          onClick={(e) => e.stopPropagation()}
          disabled={node.disabled}
          className="h-5 w-5 border-2 border-foreground data-[state=checked]:bg-primary data-[state=checked]:shadow-[2px_2px_0px_hsl(var(--shadow-color))]"
        />
      )}

      {/* Icon */}
      {showIcons && (
        <span className="shrink-0">
          {node.icon || (hasChildren ? (
            <Folder className="h-4 w-4" />
          ) : (
            <File className="h-4 w-4" />
          ))}
        </span>
      )}

      {/* Label */}
      <span className="text-sm truncate">{node.label}</span>
    </div>
  )

  if (!hasChildren) {
    return content
  }

  return (
    <Collapsible open={isExpanded} onOpenChange={() => toggleExpanded(node.id)}>
      <CollapsibleTrigger asChild className="w-full">
        {content}
      </CollapsibleTrigger>
      <CollapsibleContent>
        <div role="group">
          {node.children!.map((child) => (
            <TreeNodeItem key={child.id} node={child} level={level + 1} />
          ))}
        </div>
      </CollapsibleContent>
    </Collapsible>
  )
}

export { TreeView, useTreeView }
