// packages/vue/src/components/ui/Rating.vue
<script setup lang="ts">
import { ref, computed, watch } from 'vue'
import { cva, type VariantProps } from 'class-variance-authority'
import { cn } from '@/lib/utils'
import { Star, Heart, Circle } from 'lucide-vue-next'

const ratingVariants = cva('flex items-center gap-0.5', {
  variants: {
    size: {
      sm: '[&_svg]:h-4 [&_svg]:w-4',
      md: '[&_svg]:h-5 [&_svg]:w-5',
      lg: '[&_svg]:h-6 [&_svg]:w-6',
      xl: '[&_svg]:h-8 [&_svg]:w-8',
    },
  },
  defaultVariants: {
    size: 'md',
  },
})

type RatingVariants = VariantProps<typeof ratingVariants>

const iconMap = {
  star: Star,
  heart: Heart,
  circle: Circle,
} as const

interface RatingProps {
  modelValue?: number
  defaultValue?: number
  max?: number
  precision?: 0.5 | 1
  icon?: 'star' | 'heart' | 'circle'
  size?: RatingVariants['size']
  readOnly?: boolean
  disabled?: boolean
  class?: string
}

const props = withDefaults(defineProps<RatingProps>(), {
  defaultValue: 0,
  max: 5,
  precision: 1,
  icon: 'star',
  size: 'md',
  readOnly: false,
  disabled: false,
})

const emit = defineEmits<{
  'update:modelValue': [value: number]
  'hoverChange': [value: number | null]
}>()

const internalValue = ref(props.defaultValue)
const hoverValue = ref<number | null>(null)

const isControlled = computed(() => props.modelValue !== undefined)
const currentValue = computed(() => isControlled.value ? props.modelValue! : internalValue.value)
const displayValue = computed(() => hoverValue.value ?? currentValue.value)

const IconComponent = computed(() => iconMap[props.icon])

const iconNoun = computed(() => (props.icon === 'heart' ? 'hearts' : props.icon === 'circle' ? 'circles' : 'stars'))
const valueText = computed(() => `${currentValue.value} out of ${props.max} ${iconNoun.value}`)

// Sync internal value when modelValue changes
watch(() => props.modelValue, (newValue) => {
  if (newValue !== undefined) {
    internalValue.value = newValue
  }
})

const handleClick = (index: number, isHalf: boolean) => {
  if (props.readOnly || props.disabled) return

  const newValue = isHalf && props.precision === 0.5 ? index + 0.5 : index + 1

  if (!isControlled.value) {
    internalValue.value = newValue
  }
  emit('update:modelValue', newValue)
}

const handleMouseMove = (e: MouseEvent, index: number) => {
  if (props.readOnly || props.disabled) return

  const button = (e.target as Element)?.closest('button') as HTMLButtonElement | null
  if (!button) return
  const rect = button.getBoundingClientRect()
  const isHalf = e.clientX - rect.left < rect.width / 2

  const newHoverValue = isHalf && props.precision === 0.5 ? index + 0.5 : index + 1
  hoverValue.value = newHoverValue
  emit('hoverChange', newHoverValue)
}

const handleMouseLeave = () => {
  if (props.readOnly || props.disabled) return
  hoverValue.value = null
  emit('hoverChange', null)
}

const handleKeyDown = (e: KeyboardEvent) => {
  if (props.readOnly || props.disabled) return

  let newValue = currentValue.value

  switch (e.key) {
    case 'ArrowRight':
    case 'ArrowUp':
      e.preventDefault()
      newValue = Math.min(currentValue.value + props.precision, props.max)
      break
    case 'ArrowLeft':
    case 'ArrowDown':
      e.preventDefault()
      newValue = Math.max(currentValue.value - props.precision, 0)
      break
    case 'Home':
      e.preventDefault()
      newValue = 0
      break
    case 'End':
      e.preventDefault()
      newValue = props.max
      break
    default:
      return
  }

  if (!isControlled.value) {
    internalValue.value = newValue
  }
  emit('update:modelValue', newValue)
}

const handleIconClick = (e: MouseEvent, index: number) => {
  const button = (e.target as Element)?.closest('button') as HTMLButtonElement | null
  if (!button) return
  const rect = button.getBoundingClientRect()
  const isHalf = e.clientX - rect.left < rect.width / 2
  handleClick(index, isHalf)
}

const getFillState = (index: number) => {
  const fillValue = displayValue.value - index
  return {
    isFilled: fillValue >= 1,
    isHalfFilled: fillValue > 0 && fillValue < 1,
  }
}

const getClipPath = (isHalfFilled: boolean) => {
  return isHalfFilled ? { clipPath: 'polygon(0 0, 50% 0, 50% 100%, 0 100%)' } : undefined
}
</script>

<template>
  <div
    role="slider"
    aria-label="Rating"
    :aria-valuemin="0"
    :aria-valuemax="max"
    :aria-valuenow="currentValue"
    :aria-valuetext="valueText"
    :tabindex="readOnly || disabled ? -1 : 0"
    :class="cn(
      ratingVariants({ size }),
      disabled && 'opacity-50 pointer-events-none',
      !readOnly && !disabled && 'cursor-pointer',
      props.class
    )"
    @keydown="handleKeyDown"
    @mouseleave="handleMouseLeave"
  >
    <button
      v-for="index in max"
      :key="index - 1"
      type="button"
      :aria-label="`${index} ${icon === 'star' ? 'star' : icon === 'heart' ? 'heart' : 'circle'}${index !== 1 ? 's' : ''}`"
      :tabindex="-1"
      :disabled="disabled || readOnly"
      :class="cn(
        'relative transition-transform duration-150 focus:outline-none',
        !readOnly && !disabled && 'hover:scale-110'
      )"
      @click="handleIconClick($event, index - 1)"
      @mousemove="handleMouseMove($event, index - 1)"
    >
      <!-- Empty icon (background) -->
      <component
        :is="IconComponent"
        :class="cn(
          'stroke-foreground stroke-[2px] fill-muted transition-colors duration-150'
        )"
      />

      <!-- Filled icon (overlay) -->
      <component
        v-if="getFillState(index - 1).isFilled || getFillState(index - 1).isHalfFilled"
        :is="IconComponent"
        :class="cn(
          'absolute inset-0 stroke-foreground stroke-[2px] fill-primary transition-colors duration-150'
        )"
        :style="getClipPath(getFillState(index - 1).isHalfFilled)"
      />
    </button>
  </div>
</template>

// src/components/ui/rating.tsx
import * as React from 'react'
import { cn } from '@/lib/utils'

// ── Icons ────────────────────────────────────────────────────────────────────

function StarIcon({ filled, half }: { filled: boolean; half?: boolean }) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 24 24"
      aria-hidden="true"
    >
      {half ? (
        <>
          <defs>
            <linearGradient id="half-star">
              <stop offset="50%" stopColor="currentColor" />
              <stop offset="50%" stopColor="transparent" />
            </linearGradient>
          </defs>
          <path
            d="M12 2l3.09 6.26L22 9.27l-5 4.87 1.18 6.88L12 17.77l-6.18 3.25L7 14.14 2 9.27l6.91-1.01L12 2z"
            fill="url(#half-star)"
            stroke="currentColor"
            strokeWidth="2"
            strokeLinecap="round"
            strokeLinejoin="round"
          />
        </>
      ) : (
        <path
          d="M12 2l3.09 6.26L22 9.27l-5 4.87 1.18 6.88L12 17.77l-6.18 3.25L7 14.14 2 9.27l6.91-1.01L12 2z"
          fill={filled ? 'currentColor' : 'none'}
          stroke="currentColor"
          strokeWidth="2"
          strokeLinecap="round"
          strokeLinejoin="round"
        />
      )}
    </svg>
  )
}

function HeartIcon({ filled }: { filled: boolean }) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 24 24"
      aria-hidden="true"
    >
      <path
        d="M20.84 4.61a5.5 5.5 0 0 0-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 0 0-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 0 0 0-7.78z"
        fill={filled ? 'currentColor' : 'none'}
        stroke="currentColor"
        strokeWidth="2"
        strokeLinecap="round"
        strokeLinejoin="round"
      />
    </svg>
  )
}

function CircleIcon({ filled }: { filled: boolean }) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 24 24"
      aria-hidden="true"
    >
      <circle
        cx="12"
        cy="12"
        r="10"
        fill={filled ? 'currentColor' : 'none'}
        stroke="currentColor"
        strokeWidth="2"
      />
    </svg>
  )
}

// ── Types ────────────────────────────────────────────────────────────────────

type IconType = 'star' | 'heart' | 'circle'
type SizeVariant = 'sm' | 'md' | 'lg' | 'xl'

interface RatingProps {
  /** Controlled value */
  value?: number
  /** Uncontrolled default value */
  defaultValue?: number
  /** Maximum number of icons (default 5) */
  max?: number
  /** Precision: 1 for whole, 0.5 for half stars */
  precision?: number
  /** Icon type */
  icon?: IconType
  /** Size variant */
  size?: SizeVariant
  /** Disable interactions */
  readOnly?: boolean
  /** Disable completely */
  disabled?: boolean
  /** Called when value changes */
  onChange?: (value: number) => void
  /** Called when hover value changes (null = mouse left) */
  onHoverChange?: (value: number | null) => void
  className?: string
}

const sizeClasses: Record<SizeVariant, string> = {
  sm: '[&_svg]:h-4 [&_svg]:w-4',
  md: '[&_svg]:h-5 [&_svg]:w-5',
  lg: '[&_svg]:h-6 [&_svg]:w-6',
  xl: '[&_svg]:h-8 [&_svg]:w-8',
}

const iconLabel: Record<IconType, string> = {
  star: 'stars',
  heart: 'hearts',
  circle: 'circles',
}

// ── Component ────────────────────────────────────────────────────────────────

export function Rating({
  value: controlledValue,
  defaultValue = 0,
  max = 5,
  precision = 1,
  icon = 'star',
  size = 'md',
  readOnly = false,
  disabled = false,
  onChange,
  onHoverChange,
  className,
}: RatingProps) {
  const isControlled = controlledValue !== undefined
  const [internalValue, setInternalValue] = React.useState(defaultValue)

  const currentValue = isControlled ? controlledValue! : internalValue

  const setValue = (next: number) => {
    if (!isControlled) setInternalValue(next)
    onChange?.(next)
  }

  const interactive = !readOnly && !disabled

  const handleKeyDown = (e: React.KeyboardEvent) => {
    if (!interactive) return
    const step = precision
    let next = currentValue
    if (e.key === 'ArrowRight' || e.key === 'ArrowUp') {
      next = Math.min(max, currentValue + step)
      e.preventDefault()
    } else if (e.key === 'ArrowLeft' || e.key === 'ArrowDown') {
      next = Math.max(0, currentValue - step)
      e.preventDefault()
    } else if (e.key === 'Home') {
      next = 0
      e.preventDefault()
    } else if (e.key === 'End') {
      next = max
      e.preventDefault()
    } else {
      return
    }
    setValue(next)
  }

  const handleMouseLeave = () => {
    onHoverChange?.(null)
  }

  const handleStarMouseMove = (_e: React.MouseEvent<HTMLButtonElement>, starIndex: number) => {
    if (!interactive) return
    onHoverChange?.(starIndex)
  }

  const handleStarClick = (starIndex: number) => {
    if (!interactive) return
    setValue(starIndex)
  }

  const valueText =
    icon === 'heart'
      ? `${currentValue} out of ${max} hearts`
      : icon === 'circle'
        ? `${currentValue} out of ${max} circles`
        : `${currentValue} out of ${max} stars`

  function renderIcon(index: number) {
    const filled = index <= currentValue
    const half = !filled && index - 0.5 <= currentValue && precision === 0.5
    if (icon === 'heart') return <HeartIcon filled={filled} />
    if (icon === 'circle') return <CircleIcon filled={filled} />
    return <StarIcon filled={filled} half={half} />
  }

  return (
    <div
      role="slider"
      aria-label="Rating"
      aria-valuemin={0}
      aria-valuemax={max}
      aria-valuenow={currentValue}
      aria-valuetext={valueText}
      tabIndex={disabled || readOnly ? -1 : 0}
      onKeyDown={handleKeyDown}
      onMouseLeave={handleMouseLeave}
      className={cn(
        'flex items-center gap-0.5 outline-none',
        sizeClasses[size],
        disabled && 'opacity-50 pointer-events-none',
        className
      )}
    >
      {Array.from({ length: max }, (_, i) => {
        const starIndex = i + 1
        const isSelected = starIndex === Math.ceil(currentValue)
        const isFocusable = interactive && (currentValue === 0 ? starIndex === 1 : isSelected)
        return (
          <button
            key={starIndex}
            type="button"
            tabIndex={isFocusable ? 0 : -1}
            disabled={disabled}
            aria-label={`${starIndex} ${iconLabel[icon]}`}
            onClick={() => handleStarClick(starIndex)}
            onMouseMove={(e) => handleStarMouseMove(e, starIndex)}
            className={cn(
              'flex items-center justify-center transition-transform focus:outline-none',
              interactive && 'hover:scale-110 cursor-pointer',
              !interactive && 'cursor-default'
            )}
          >
            {renderIcon(starIndex)}
          </button>
        )
      })}
    </div>
  )
}
